// lib/chatbot/additionalKnowledge.ts

import type { SiteLanguage } from "@/lib/content/profile";
import type { ChatKnowledgeItem } from "@/lib/chatbot/types";

type KnowledgeEntry = {
  id: string;
  priority: number;
  translations: Record<SiteLanguage, { answer: string; terms: string[] }>;
};

const rawKnowledgeEntries: readonly KnowledgeEntry[] = [
  {
    id: "additional-next-role",
    priority: 12,
    translations: {
      en: {
        answer:
          "Magnus is primarily searching for roles in business development, commercial leadership, and project management. And he prefers situations where the business or operations have development potential.",
        terms: [
          "next role",
          "next job",
          "roles Magnus is looking for",
          "what roles is Magnus looking for",
          "what positions is Magnus looking for",
          "what job is Magnus looking for",
          "what does Magnus want to work with",
          "what does Magnus want to work on",
          "what kind of role does Magnus want",
          "what does Magnus want to do next",
          "career interests",
          "job interests",
          "project management role",
          "business development role",
          "commercial leadership role",
          "commercial roles",
        ],
      },
      sv: {
        answer:
          "Magnus söker framför allt roller inom affärsutveckling, kommersiell ledning och projektledning. Och det han finner mest lockande är roller där affär och verksamhet har utvecklingspotential.",
        terms: [
          "nästa roll",
          "nästa jobb",
          "vilka roller söker Magnus",
          "vilka jobb söker Magnus",
          "vad söker Magnus för jobb",
          "vad vill Magnus arbeta med",
          "vad vill Magnus jobba med",
          "vilken typ av roll vill Magnus ha",
          "vad vill Magnus göra härnäst",
          "karriärintressen",
          "jobbsök",
          "projektledningsroll",
          "affärsutvecklingsroll",
          "kommersiell ledning",
          "kommersiella roller",
        ],
      },
    },
  },
  {
    id: "additional-leadership-style",
    priority: 11,
    translations: {
      en: {
        answer:
          "As a leader, Magnus is clear, attentive, fair, and inclusive. He practices and expects direct communication and honesty, and advocates autonomy with accountability.",
        terms: [
          "leadership style",
          "how does Magnus lead",
          "leadership",
          "build trust",
          "trust based leadership",
          "people leadership",
          "leadership philosophy",
          "how is Magnus as a manager",
          "managerial style",
          "how is Magnus as a leader",
          "how would Magnus describe his leadership",
          "build trust as a leader",
          "trust in leadership",
          "what is Magnus like as a leader",
        ],
      },
      sv: {
        answer:
          "Som ledare är Magnus tydlig, lyhörd, rättvis och involverande. Han tillämpar samt förväntar sig rak kommunikation och ärlighet, och förespråkar frihet under ansvar.",
        terms: [
          "ledarskapsstil",
          "hur leder Magnus",
          "ledarskap",
          "skapa förtroende",
          "personalledning",
          "ledarstil",
          "ledarskapsfilosofi",
          "hur är Magnus som chef",
          "chefstil",
          "hur är Magnus som ledare",
          "hur skulle Magnus beskriva sitt ledarskap",
          "bygga tillit som ledare",
          "tillit i ledarskap",
        ],
      },
    },
  },
  {
    id: "additional-formal-people-management",
    priority: 14,
    translations: {
      en: {
        answer:
          "Magnus has held formal people-management responsibility as Marketing Manager and acting CEO at Bahnhof Unipessoal Lda., based in Funchal, Portugal, and as Chief Commercial Officer at TH1NG AB (publ).",
        terms: [
          "formal people management",
          "people management responsibility",
          "personnel responsibility",
          "staff responsibility",
          "line management",
          "direct reports",
          "managed employees",
          "Bahnhof Unipessoal",
          "acting CEO",
          "interim CEO",
          "has Magnus been a manager",
          "has Magnus had people management responsibility",
          "has Magnus managed people",
          "what management experience does Magnus have",
          "what management roles has Magnus had",
        ],
      },
      sv: {
        answer:
          "Magnus har haft formellt personalansvar som marknadschef och tillförordnad VD på Bahnhof Unipessoal Lda., i Funchal, Portugal, och som Chief Commercial Officer på TH1NG AB (publ).",
        terms: [
          "formellt personalansvar",
          "personalansvar",
          "chefserfarenhet",
          "linjechef",
          "direktrapporterande",
          "lett personal",
          "Bahnhof Unipessoal",
          "tillförordnad vd",
          "tf vd",
          "vd-roll",
          "har Magnus varit chef",
          "har Magnus haft personalansvar",
          "vilka chefsroller har Magnus haft",
          "vilken chefserfarenhet har Magnus",
        ],
      },
    },
  },
  {
    id: "additional-resistance-and-difficult-decisions",
    priority: 10,
    translations: {
      en: {
        answer:
          "When Magnus encounters resistance, he tries to approach the issue from different perspectives. He also consults others for advice and additional points of view. When decisions are required to deliver on an assignment, he takes a pragmatic view of the task and the circumstances at hand rather than being guided by emotions.",
        terms: [
          "handle resistance",
          "dealing with resistance",
          "how does Magnus handle resistance",
          "difficult decisions",
          "hard decisions",
          "how does Magnus make difficult decisions",
          "decision making under pressure",
        ],
      },
      sv: {
        answer:
          "I situationer när Magnus möter motstånd, försöker han angripa frågan från olika perspektiv. Han stämmer även av med andra för tips och ytterligare infallsvinklar. När beslut krävs för att leverera på ett uppdrag, förhåller han sig krasst till uppgiften och rådande förutsättningar snarare än att vägledas av känslor.",
        terms: [
          "hantera motstånd",
          "motstånd",
          "hur hanterar Magnus motstånd",
          "svåra beslut",
          "jobbiga beslut",
          "hur fattar Magnus svåra beslut",
          "beslutsfattande under press",
        ],
      },
    },
  },
  {
    id: "additional-project-management-approach",
    priority: 14,
    translations: {
      en: {
        answer:
          "When Magnus takes responsibility for a new project, he starts by establishing a clear understanding of its scope, framework, and timeline. He develops a project plan and combines a clear foundational structure with ongoing revisions to avoid surprises. Throughout the project, he stress-tests different elements and deliverables to maintain control.",
        terms: [
          "project management approach",
          "how does Magnus manage projects",
          "how does Magnus run projects",
          "new project",
          "starting a project",
          "how does Magnus start a project",
          "project plan",
          "project planning",
          "timeline planning",
          "project structure",
          "project follow up",
          "how does Magnus work with project management",
        ],
      },
      sv: {
        answer:
          "När Magnus får ansvar för ett nytt projekt börjar han med att skapa en bild av omfattning, ramverk och tidsplan. Han arbetar fram en projektplan och kombinerar en tydlig grundstruktur med löpande revideringar för att söka undvika överraskningar. Under projektets gång trycktestar han olika delar och leveranser för att bibehålla kontroll.",
        terms: [
          "projektledning",
          "hur arbetar Magnus med projektledning",
          "hur driver Magnus projekt",
          "nytt projekt",
          "starta ett projekt",
          "hur börjar Magnus ett projekt",
          "projektplan",
          "projektplanering",
          "tidsplan",
          "projektstruktur",
          "projektuppföljning",
        ],
      },
    },
  },
  {
    id: "additional-strategy-execution-strength",
    priority: 11,
    translations: {
      en: {
        answer:
          "Magnus’s primary strength is his ability to quickly take action and drive things forward. He starts with a rapid analysis to build an understanding of the situation and the prevailing conditions, then moves into execution. Analysis and structuring continue in parallel with the work, allowing him to combine decisiveness and pace with a structured way of working.",
        terms: [
          "strategy execution",
          "analysis or execution",
          "analysis strength",
          "structuring",
          "execution strength",
          "getting started",
          "strategic execution",
          "analytical or execution oriented",
          "is Magnus more analytical or execution oriented",
          "analysis to execution",
          "take action",
          "drive things forward",
          "execution focus",
        ],
      },
      sv: {
        answer:
          "Magnus främsta styrka är att snabbt ta tag i saker och driva dem framåt. Han börjar med en snabb analys för att skapa en bild av situationen och rådande förutsättningar och går därefter över i genomförande. Analys och strukturering fortsätter parallellt med arbetet, vilket gör att han kan kombinera handlingskraft och tempo med ett strukturerat arbetssätt.",
        terms: [
          "strategigenomförande",
          "strategiexekvering",
          "analys eller genomförande",
          "analysstyrka",
          "strukturering",
          "genomförande",
          "komma igång",
          "handlingskraft",
          "driva saker framåt",
          "genomförandefokus",
        ],
      },
    },
  },
  {
    id: "additional-change-environments",
    priority: 10,
    translations: {
      en: {
        answer:
          "Magnus has worked in changing environments throughout much of his career and views change as a natural part of working life rather than something exceptional. Change can lead to duplicated efforts and create uncertainty, but his primary focus is on what the situation requires and what needs to be done.",
        terms: [
          "change",
          "change management",
          "changing environment",
          "transformation",
          "organizational change",
          "working with change",
          "changing environments",
          "does Magnus thrive in changing environments",
          "how does Magnus view change",
        ],
      },
      sv: {
        answer:
          "Magnus har arbetat i föränderliga miljöer under stora delar av sin karriär och betraktar förändring mer som ett naturligt inslag i arbetslivet än någonting exceptionellt. Förändring kan medföra dubbelarbete och skapa ovisshet, men han fokuserar framför allt på vad situationen kräver och vad som behöver göras.",
        terms: [
          "förändring",
          "förändringsledning",
          "föränderlig miljö",
          "transformation",
          "organisationsförändring",
          "arbeta med förändring",
          "föränderliga miljöer",
          "trivs Magnus i föränderliga miljöer",
          "hur ser Magnus på förändring",
        ],
      },
    },
  },
  {
    id: "additional-commercial-strengths",
    priority: 14,
    translations: {
      en: {
        answer:
          "Magnus sees business development, pricing strategy, and commercial agreements as particularly strong competence areas.",
        terms: [
          "commercial strengths",
          "business development",
          "pricing",
          "pricing strategy",
          "commercial agreements",
          "contracts",
          "contract development",
          "strongest commercial areas",
          "what is Magnus best at commercially",
          "which commercial areas is Magnus strongest in",
        ],
      },
      sv: {
        answer:
          "Magnus bedömer affärsutveckling, prisstrategi och kommersiella avtal som väldigt starka kompetensområden.",
        terms: [
          "kommersiella styrkor",
          "affärsutveckling",
          "prissättning",
          "prisstrategi",
          "kommersiella avtal",
          "avtal",
          "avtalsutveckling",
          "starkaste kommersiella områden",
          "vad är Magnus bäst på kommersiellt",
          "vilka kommersiella områden är Magnus starkast inom",
        ],
      },
    },
  },
  {
    id: "additional-cross-functional-work",
    priority: 13,
    translations: {
      en: {
        answer:
          "Magnus values cross-functional work because different perspectives and areas of expertise provide a broader understanding, more potential solutions, and better alignment. He also sees it as a valuable way to develop his own knowledge.",
        terms: [
          "cross-functional work",
          "cross-functional collaboration",
          "working cross functionally",
          "work cross functionally",
          "cross-functional",
          "how does Magnus work cross functionally",
          "how does Magnus collaborate across functions",
          "collaboration across functions",
          "alignment across functions",
          "cross-functional alignment",
        ],
      },
      sv: {
        answer:
          "Magnus uppskattar tvärfunktionellt arbete eftersom olika perspektiv och kompetenser ger en bredare förståelse, fler möjliga lösningar och bättre samsyn. Han ser det också som ett värdefullt sätt att utveckla sin egen kunskap.",
        terms: [
          "tvärfunktionellt arbete",
          "tvärfunktionellt samarbete",
          "arbeta tvärfunktionellt",
          "jobba tvärfunktionellt",
          "tvärfunktionellt",
          "hur arbetar Magnus tvärfunktionellt",
          "hur jobbar Magnus tvärfunktionellt",
          "samarbete mellan funktioner",
          "samarbete över funktionsgränser",
          "tvärfunktionell samordning",
          "samsyn mellan funktioner",
          "tvärfunktionell samsyn",
        ],
      },
    },
  },
  {
    id: "additional-stakeholder-disagreement",
    priority: 12,
    translations: {
      en: {
        answer:
          "When stakeholders have different views on what needs to be done, or have different priorities, Magnus tries to build an overall understanding of the situation. He seeks to understand why their perspectives differ. In most cases, logical compromises can be found, but if this is not possible, the issue needs to be escalated. When Magnus has a clear mandate, he requires good reason to question it.",
terms: [
  "stakeholders disagree",
  "different priorities",
  "conflicting goals",
  "conflicting priorities",
  "disagreement between stakeholders",
  "stakeholder management",
  "how does Magnus handle stakeholder disagreement",
  "how does Magnus handle conflicting goals",
  "how does Magnus handle different priorities",
  "stakeholder conflict",
]
      },
      sv: {
        answer:
          "När intressenter har olika syn på vad som behöver göras, eller har olika prioriteringar, försöker Magnus skapa en övergripande bild av situationen. Han vill förstå varför uppfattningarna skiljer sig åt. I de flesta fall går det att hitta logiska kompromisser, men om det inte går får frågan eskaleras. När Magnus har ett tydligt uppdrag, krävs goda skäl för att han ska ifrågasätta det.",
terms: [
  "intressenter oense",
  "olika prioriteringar",
  "motstridiga mål",
  "motstridiga prioriteringar",
  "oenighet mellan intressenter",
  "intressenthantering",
  "hur hanterar Magnus oenighet mellan intressenter",
  "hur hanterar Magnus motstridiga mål",
  "hur hanterar Magnus olika prioriteringar",
  "konflikt mellan intressenter",
]
      },
    },
  },
  {
    id: "additional-preferred-work-environment",
    priority: 12,
    translations: {
      en: {
        answer:
          "Magnus generally performs at his best in smaller organizations, as roles tend to be broader. He also values short decision-making paths and less bureaucracy. At the same time, he recognizes the advantages of larger organizations, particularly well-established central functions as well as greater financial and organizational stability.",
        terms: [
          "preferred organization",
          "company size",
          "small company",
          "large company",
          "small organization",
          "large organization",
          "small or large companies",
          "small or large organization",
          "does Magnus prefer small or large companies",
          "what type of organization does Magnus thrive in",
          "decision making paths",
          "short decision making paths",
          "bureaucracy",
        ],
      },
      sv: {
        answer:
          "Magnus kommer generellt mer till sin rätt i mindre organisationer, eftersom det i regel innebär att rollerna är bredare. Han uppskattar dessutom korta beslutsvägar och mindre byråkrati. Samtidigt ser han fördelarna med större organisationer, framför allt etablerade centrala funktioner samt ekonomisk stabilitet och trygghet.",
        terms: [
          "vilken organisation passar Magnus",
          "företagsstorlek",
          "mindre organisation",
          "större organisation",
          "små eller stora företag",
          "mindre eller större företag",
          "mindre eller större organisation",
          "föredrar Magnus små eller stora företag",
          "vilken typ av organisation trivs Magnus bäst i",
          "i vilken typ av organisation trivs Magnus bäst",
          "korta beslutsvägar",
          "beslutsvägar",
          "byråkrati",
        ],
      },
    },
  },
  {
    id: "additional-working-style",
    priority: 11,
    translations: {
      en: {
        answer:
          "Magnus prefers a combination of independent responsibility and teamwork. He often performs better when he can work independently on issues that benefit from concentrated ownership, while other questions need broader context and multiple perspectives. He also values the social exchange that comes from working with a team.",
        terms: [
          "working style",
          "independent or team",
          "teamwork",
          "independent work",
          "self directed",
          "team collaboration",
          "how does Magnus work best",
          "how does Magnus prefer to work",
          "work alone or in a team",
          "team player",
        ],
      },
      sv: {
        answer:
          "Magnus föredrar en kombination av självständigt ansvar och teamsamarbete. Han levererar ofta bättre när han kan arbeta självständigt med frågor som gynnas av koncentrerat ansvar, medan andra frågor kräver större sammanhang och flera perspektiv. Han uppskattar också det sociala utbytet som kommer av att arbeta i grupp.",
        terms: [
          "arbetssätt",
          "självständigt eller team",
          "teamarbete",
          "självständigt arbete",
          "eget ansvar",
          "grupparbete",
          "hur arbetar Magnus bäst",
          "hur föredrar Magnus att arbeta",
          "jobba själv eller i team",
          "arbeta själv eller i team",
          "lagspelare",
        ],
      },
    },
  },
  {
    id: "additional-problem-solving",
    priority: 13,
    translations: {
      en: {
        answer:
          "Magnus handles complex or ambiguous situations by building an understanding of what is known, what remains unclear, and what options are available. He considers different perspectives and assumptions, and reassesses his approach if the circumstances change.",
        terms: [
          "problem solving",
          "complex problem",
          "unclear problem",
          "ambiguous problem",
          "complex situation",
          "ambiguous situation",
          "solve problems",
          "how does Magnus solve complex problems",
          "how does Magnus approach unclear problems",
          "how does Magnus handle ambiguous situations",
          "how does Magnus work with problem solving",
        ],
      },
      sv: {
        answer:
          "Magnus hanterar komplexa eller otydliga situationer genom att skapa en bild av vad som är känt, vad som är oklart och vilka alternativ som finns. Han prövar olika perspektiv och antaganden, och omvärderar angreppssättet om förutsättningarna förändras.",
        terms: [
          "problemlösning",
          "komplext problem",
          "otydligt problem",
          "oklar uppgift",
          "komplex situation",
          "otydlig situation",
          "lösa problem",
          "hur löser Magnus komplexa problem",
          "hur angriper Magnus otydliga problem",
          "hur hanterar Magnus otydliga situationer",
          "hur arbetar Magnus med problemlösning",
        ],
      },
    },
  },
  {
    id: "additional-motivation",
    priority: 12,
    translations: {
      en: {
        answer:
          "Magnus is motivated by the fact that he contributes to the organization, continues to develop, and has clearly defined responsibility. His motivation decreases when those elements are missing, particularly when urgent tasks requiring immediate delivery repeatedly come in from the side.",
        terms: [
          "motivation",
          "what motivates Magnus",
          "motivated at work",
          "motivation at work",
          "demotivates",
          "what demotivates Magnus",
          "loses motivation",
          "what reduces Magnus motivation",
          "what drives Magnus at work",
          "what makes Magnus enjoy work",
        ],
      },
      sv: {
        answer:
          "Magnus motiveras av att känna att han bidrar till verksamheten, att han utvecklas och har ett tydligt ansvar. Motivationen minskar när de delarna saknas och inte minst när uppgifter som snarast ska levereras på kommer in från sidan.",
        terms: [
          "motivation",
          "vad motiverar Magnus",
          "motiverad på jobbet",
          "motivation på jobbet",
          "demotiverar",
          "vad demotiverar Magnus",
          "tappar motivation",
          "vad minskar Magnus motivation",
          "vad driver Magnus",
          "vad får Magnus att trivas på jobbet",
        ],
      },
    },
  },
  {
    id: "additional-self-described-strengths",
    priority: 12,
    translations: {
      en: {
        answer:
          "Magnus highlights initiative, his ability to learn quickly, decisiveness, a high work pace, and his ability to adapt quickly to new circumstances and situations as his key strengths.",
        terms: [
          "self described strengths",
          "professional strengths",
          "Magnus strengths",
          "initiative",
          "quick learner",
          "decisive",
          "high work pace",
          "work pace",
          "adaptable",
          "adapt quickly",
          "key strengths",
          "strengths",
          "what are Magnus strengths",
        ],
      },
      sv: {
        answer:
          "Magnus lyfter fram initiativförmåga, att han är lättlärd, beslutsam, har ett högt arbetstempo och snabbt anpassar sig till nya förutsättningar och situationer som främsta styrkor.",
        terms: [
          "egna styrkor",
          "professionella styrkor",
          "Magnus styrkor",
          "initiativförmåga",
          "initiativtagande",
          "lättlärd",
          "beslutsam",
          "högt arbetstempo",
          "arbetstempo",
          "anpassningsförmåga",
          "anpassar sig snabbt",
          "främsta styrkor",
          "styrkor",
          "vad är Magnus styrkor",
        ],
      },
    },
  },
  {
    id: "additional-development-areas",
    priority: 13,
    translations: {
      en: {
        answer:
          "Magnus primarily sees two development areas: being better at recognizing when other people will not deliver as expected, and planning his own time with more margin. He respects and meets deadlines, but acknowledges that his time planning can make the final phase unnecessarily stressful.",
        terms: [
          "development areas",
          "weaknesses",
          "areas to improve",
          "what can Magnus improve",
          "time planning",
          "time management",
          "deadlines",
          "what is he bad at",
          "challenges",
          "weak points",
          "what are Magnus challenges",
          "professional challenges",
        ],
      },
      sv: {
        answer:
          "Magnus ser framför allt två utvecklingsområden hos sig själv: bli bättre på att förstå när andra inte kommer att leverera som förväntat, och att planera sin egen tid med större marginal. Han respekterar och håller deadlines, men konstaterar att tidsplaneringen ibland kan göra slutskedet onödigt stressigt.",
        terms: [
          "utvecklingsområden",
          "svagheter",
          "förbättringsområden",
          "vad kan Magnus förbättra",
          "tidsplanering",
          "tidshantering",
          "deadlines",
          "vad är han dålig på",
          "utmaningar",
          "svaga sidor",
          "vad är sämre",
          "vad är Magnus utmaningar",
          "professionella utmaningar",
        ],
      },
    },
  },
  {
    id: "additional-industry-openness",
    priority: 12,
    translations: {
      en: {
        answer:
          "Magnus is open to new industries beyond telecom and IT. His commercial drive, structural mindset, and ability to quickly grasp new domain knowledge allow him to deliver value efficiently in new environments.",
        terms: [
          "other industries",
          "industry preference",
          "open to new industries",
          "work in other industries",
          "work outside telecom and IT",
          "can Magnus change industry",
          "would Magnus change industry",
          "does Magnus have to work in telecom",
          "does Magnus want to work outside telecom",
          "is Magnus open to new industries",
        ],
      },
      sv: {
        answer:
          "Magnus är helt öppen för arbete inom andra branscher än telekom och IT. Hans kommersiella driv, struktur och förmåga att snabbt sätta sig in i nya områden gör att han effektivt skapar värde även i nya miljöer.",
        terms: [
          "andra branscher",
          "branschpreferens",
          "öppen för nya branscher",
          "arbeta i andra branscher",
          "arbeta utanför telekom och IT",
          "kan Magnus byta bransch",
          "vill Magnus byta bransch",
          "måste Magnus arbeta inom telekom",
          "måste Magnus jobba inom telekom",
          "är Magnus öppen för nya branscher",
        ],
      },
    },
  },
  {
    id: "additional-location-flexibility",
    priority: 15,
    translations: {
      en: {
        answer:
          "Stockholm is Magnus's base and he is not relocatable. He can, however, work on site in other locations and travel.",
        terms: [
          "location flexibility",
          "relocate",
          "relocation",
          "relocatable",
          "can Magnus relocate",
          "work in another city",
          "work elsewhere",
          "travel for work",
          "Stockholm base",
          "geographically flexible",
          "is Magnus geographically flexible",
        ],
      },
      sv: {
        answer:
          "Stockholm är Magnus bas och han är inte flyttbar. Däremot är han öppen för arbete på annan ort och resor.",
        terms: [
          "geografisk flexibilitet",
          "flytta",
          "flyttbar",
          "kan Magnus flytta",
          "arbeta på annan ort",
          "jobba på annan ort",
          "resor i jobbet",
          "Stockholm bas",
          "geografiskt flexibel",
          "är Magnus geografiskt flexibel",
        ],
      },
    },
  },
  {
    id: "additional-hybrid-remote",
    priority: 13,
    translations: {
      en: {
        answer:
          "Magnus prefers a hybrid setup of office presence and remote work. He feels that fully remote work reduces context, community, and useful synergies, although he remains open to different arrangements rather than setting rigid rules.",
        terms: [
          "hybrid",
          "remote",
          "remote work",
          "fully remote",
          "work from home",
          "working arrangement",
          "hybrid work",
          "office or remote",
          "office or home",
          "does Magnus want to work remotely",
        ],
      },
      sv: {
        answer:
          "Magnus föredrar ett hybridupplägg av kontorsnärvaro och distansarbete. Han menar att fullständigt distansarbete sker på bekostnad av sammanhang, gemenskap och synergier, men är samtidigt öppen för olika upplägg och har inga låsta ramar.",
        terms: [
          "hybrid",
          "remote",
          "distansarbete",
          "helt på distans",
          "jobba hemifrån",
          "arbetsupplägg",
          "hybridarbete",
          "distans",
          "kontor eller distans",
          "kontor eller hemma",
          "vill Magnus arbeta på distans",
          "vill Magnus jobba på distans",
        ],
      },
    },
  },
  {
    id: "additional-availability",
    priority: 18,
    translations: {
      en: {
        answer: "Magnus is available to start immediately.",
        terms: [
          "availability",
          "available to start",
          "when can Magnus start",
          "start date",
          "notice period",
          "immediately available",
        ],
      },
      sv: {
        answer: "Magnus är tillgänglig omgående.",
        terms: [
          "tillgänglighet",
          "tillgänglig omgående",
          "när kan Magnus börja",
          "startdatum",
          "uppsägningstid",
          "börja omgående",
        ],
      },
    },
  },
  {
    id: "additional-languages-practical",
    priority: 14,
    translations: {
      en: {
        answer:
          "Magnus speaks Swedish natively and English professionally. His German is limited, although he understands a fair amount, while his Spanish and Portuguese are very limited.",
        terms: [
          "languages",
          "English professionally",
          "professional English",
          "can Magnus work in English",
          "German",
          "Spanish",
          "Portuguese",
          "Swedish",
          "native language",
          "language skills",
          "what languages does Magnus speak",
          "what languages does Magnus know",
          "can Magnus speak English",
          "native Swedish",
        ],
      },
      sv: {
        answer:
          "Magnus har svenska som modersmål samtidigt som han behärskar engelska på professionell nivå. Hans tyska är begränsad, även om han förstår en del, medan hans spanska och portugisiska är väldigt begränsade.",
        terms: [
          "språk",
          "engelska professionellt",
          "professionell engelska",
          "kan Magnus arbeta på engelska",
          "tyska",
          "spanska",
          "portugisiska",
          "svenska",
          "modersmål",
          "språkkunskaper",
          "vilka språk talar Magnus",
          "vilka språk kan Magnus",
          "kan Magnus engelska",
          "svenska som modersmål",
        ],
      },
    },
  },
  {
    id: "additional-interests",
    priority: 12,
    translations: {
      en: {
        answer:
          "Outside work, Magnus spends time with family and friends. He trains at the gym and runs, and during the winter he skis downhill and cross-country. He listens to a lot of popular music, plays some guitar and also practices card tricks.",
        terms: [
          "hobbies",
          "free time",
          "outside work",
          "family and friends",
          "gym",
          "running",
          "skiing",
          "downhill skiing",
          "cross country skiing",
          "music",
          "guitar",
          "card magic",
          "card tricks",
          "card illusions",
          "free time interests",
          "what are Magnus interests",
          "what interests does Magnus have",
          "does Magnus have hobbies",
          "interests outside work",
        ],
      },
      sv: {
        answer:
          "På fritiden spenderar Magnus tid med familj och vänner. Han tränar på gym och löptränar, tycker om utförsåkning och längdskidor. Han lyssnar mycket på populärmusik, spelar lite gitarr och håller på med korttrick.",
        terms: [
          "hobbys",
          "fritid",
          "utanför jobbet",
          "familj och vänner",
          "gym",
          "löpning",
          "skidor",
          "utförsåkning",
          "längdskidor",
          "musik",
          "gitarr",
          "korttrolleri",
          "korttrick",
          "kortillusioner",
          "fritidsintressen",
          "vad har Magnus för intressen",
          "vilka intressen har Magnus",
          "har Magnus några hobbies",
          "hobbies",
          "intressen på fritiden",
        ],
      },
    },
  },
  {
    id: "additional-personality-outside-work",
    priority: 11,
    translations: {
      en: {
        answer:
          "Magnus thinks people who know him well would describe him as social, pleasant, respectful, and someone they can trust. They would probably also call him a time optimist who can arrive a little later than agreed.",
        terms: [
          "personality outside work",
          "what is Magnus like personally",
          "friends describe Magnus",
          "what would others say about Magnus",
          "how would others describe Magnus",
          "how would people who know Magnus describe him",
          "trustworthy",
          "time optimist",
          "does Magnus arrive late",
          "is Magnus a time optimist",
          "Magnus personally",
          "personal life personality",
        ],
      },
      sv: {
        answer:
          "Magnus tror att människor som känner honom väl skulle beskriva honom som social, trevlig, respektfull och en person de kan lita på. De skulle sannolikt också beskriva honom som en tidsoptimist som ibland kommer lite senare än överenskommet.",
        terms: [
          "personlighet utanför jobbet",
          "hur är Magnus privat",
          "hur beskriver vänner Magnus",
          "vad skulle andra säga om Magnus",
          "hur skulle andra beskriva Magnus",
          "hur skulle personer som känner Magnus beskriva honom",
          "pålitlig",
          "tidsoptimist",
          "kommer Magnus sent",
          "är Magnus tidsoptimist",
          "Magnus privat",
          "privat personlighet",
        ],
      },
    },
  },
  {
    id: "additional-parachute-ranger-impact",
    priority: 13,
    translations: {
      en: {
        answer:
          "Magnus believes his parachute-ranger service taught him that people can handle considerably more than they initially think. He sees that experience as a big reason it takes a great deal for him to give up when something is challenging.",
        terms: [
          "parachute ranger",
          "military service",
          "military background",
          "ranger service",
          "giving up",
          "not give up",
          "how has parachute ranger service affected Magnus",
          "military experience",
          "what has Magnus military background taught him",
        ],
      },
      sv: {
        answer:
          "Magnus upplever att fallskärmsjägartjänsten lärde honom att man klarar betydligt mer än man först föreställer sig. Han ser den erfarenheten som en stor anledning till varför det krävs mycket för att han ska ge upp när någonting är utmanande.",
        terms: [
          "fallskärmsjägare",
          "militärtjänst",
          "militär bakgrund",
          "jägartjänst",
          "ge upp",
          "inte ge upp",
          "hur har fallskärmsjägartjänsten påverkat Magnus",
          "militärbakgrund",
          "vad har Magnus militärbakgrund gett honom",
        ],
      },
    },
  },
  {
    id: "additional-career-breadth",
    priority: 13,
    translations: {
      en: {
        answer:
          "Magnus has worked broadly across sales, business development, strategy, marketing, as well as legal and regulatory matters. He performs best in roles where he can combine multiple areas and work with a variety of issues rather than within a narrowly defined function.",
        terms: [
          "career choices",
          "career breadth",
          "why different roles",
          "sales business development strategy marketing",
          "legal regulatory",
          "broad experience",
          "broad roles",
          "multiple areas",
          "varied issues",
          "combine multiple areas",
        ],
      },
      sv: {
        answer:
          "Magnus har arbetat brett inom försäljning, affärsutveckling, strategi, marknad samt juridiska och regulatoriska frågor. Han trivs bäst i roller där han får kombinera flera områden och arbeta med varierande frågeställningar snarare än inom en smalt avgränsad funktion.",
        terms: [
          "karriärval",
          "karriärbredd",
          "varför olika roller",
          "försäljning affärsutveckling strategi marknad",
          "juridik regulatorik",
          "bred erfarenhet",
          "breda roller",
          "flera områden",
          "varierande frågeställningar",
          "kombinera flera områden",
        ],
      },
    },
  },
  {
    id: "additional-differentiator",
    priority: 16,
    translations: {
      en: {
        answer:
          "Magnus’s primary differentiator is his ability to quickly understand a new situation and turn that understanding into action. He has a short ramp-up time, a high work capacity, and a strong execution focus, which enables him to create momentum quickly even in new or ambiguous situations. At the same time, he combines this high pace with accessibility and genuine engagement with the colleagues around him.",
        terms: [
          "what makes Magnus different",
          "different from other candidates",
          "differentiator",
          "why hire Magnus",
          "unique strength",
          "candidate comparison",
          "main differentiator",
          "what is Magnus main differentiator",
          "why should we hire Magnus",
        ],
      },
      sv: {
        answer:
          "Magnus främsta differentiator är hans förmåga att snabbt förstå en ny situation och omsätta den förståelsen i handling. Han har kort startsträcka, hög arbetskapacitet och ett starkt genomförandefokus, vilket gör att han snabbt kan börja skapa framdrift även i nya eller otydliga sammanhang. Samtidigt kombinerar han det höga tempot med tillgänglighet och ett genuint engagemang för kollegorna omkring sig.",
        terms: [
          "vad skiljer Magnus från andra",
          "skillnad mot andra kandidater",
          "varför anställa Magnus",
          "unik styrka",
          "kandidatjämförelse",
          "vad gör Magnus annorlunda",
          "differentiator",
          "främsta differentiator",
          "vad är Magnus främsta differentiator",
          "varför ska vi anställa Magnus",
        ],
      },
    },
  },
  {
    id: "additional-salary-expectations",
    priority: 15,
    translations: {
      en: {
        answer:
          "Magnus's salary expectations are role-specific. Compensation is a factor, but not everything – he also values development opportunities, trust, and autonomy with accountability.",
        terms: [
          "salary",
          "salary expectations",
          "salary requirement",
          "compensation",
          "compensation expectations",
          "pay expectations",
          "expected salary",
          "what salary does Magnus expect",
          "what are Magnus's salary expectations",
          "salary range",
          "what salary does Magnus want",
          "what compensation does Magnus expect",
          "Magnus pay",
          "how does Magnus view compensation",
          "compensation for the role",
        ],
      },
      sv: {
        answer:
          "Magnus löneanspråk är rollspecifikt. Lön är en faktor, men inte allt – han värderar också utvecklingsmöjligheter, förtroende och frihet under ansvar.",
        terms: [
          "löneanspråk",
          "löneförväntan",
          "löneförväntningar",
          "ersättning",
          "vilken lön förväntar sig Magnus",
          "vad har Magnus för löneanspråk",
          "vad är Magnus löneanspråk",
          "lönekrav",
          "förväntad lön",
          "vad vill Magnus ha i lön",
          "vilken lönenivå förväntar sig Magnus",
          "Magnus lön",
          "hur ser Magnus på lön",
          "vad gäller lön",
          "lön för rollen",
        ],
      },
    },
  },
  {
    id: "additional-proudest-achievement",
    priority: 16,
    translations: {
      en: {
        answer:
          "The individual achievement Magnus is most proud of is developing and authoring a new service provider agreement at GlobalConnect that was later proposed as an industry standard by the Swedish Service Provider Association.",
        terms: [
          "proudest achievement",
          "most proud of",
          "achievement",
          "accomplishment",
          "success",
          "successful achievement",
          "what is Magnus most proud of",
          "what has Magnus achieved",
          "GlobalConnect agreement",
          "service provider agreement",
          "industry standard",
          "greatest achievement",
          "biggest achievement",
          "which achievement is Magnus most proud of",
        ],
      },
      sv: {
        answer:
          "Den enskilda prestation Magnus är mest stolt över är när han på GlobalConnect utvecklade och författade ett nytt tjänsteleverantörsavtal som senare föreslogs som branschstandard av Tjänsteleverantörsföreningen.",
        terms: [
          "stolt över",
          "mest stolt över",
          "bedrift",
          "bedrifter",
          "prestation",
          "framgång",
          "lyckats med",
          "vad är Magnus mest stolt över",
          "vad har Magnus lyckats med",
          "GlobalConnect avtal",
          "tjänsteleverantörsavtal",
          "branschstandard",
          "största bedrift",
          "största prestation",
          "främsta prestation",
          "vilken bedrift är Magnus mest stolt över",
        ],
      },
    },
  },
  {
    id: "additional-employer-preferences",
    priority: 14,
    translations: {
      en: {
        answer:
          "Magnus is looking for a financially stable employer that is focused on expansion. In addition, he values transparency and open information-sharing so that employees understand the direction of the business and the reasoning behind important decisions. He also values an open, inclusive, and social culture.",
        terms: [
          "employer preferences",
          "ideal employer",
          "what does Magnus look for in an employer",
          "what does Magnus want from an employer",
          "what matters to Magnus in an employer",
          "financially stable employer",
          "expansion",
          "transparency",
          "information sharing",
          "open information sharing",
          "open culture",
          "inclusive culture",
          "social culture",
          "what does Magnus value in an employer",
          "what type of employer is Magnus looking for",
          "what employer suits Magnus",
          "what does Magnus value in a workplace",
          "what matters to Magnus in a workplace",
          "what does Magnus appreciate in a workplace",
        ],
      },
      sv: {
        answer:
          "Magnus söker en ekonomiskt stabil arbetsgivare som satsar på expandering. Därtill värdesätter han transparens och informationsspridning för att medarbetarna ska ha förståelse för verksamhetens riktning och viktiga beslut. En öppen, inkluderande och social kultur är också någonting han värdesätter.",
        terms: [
          "vad söker Magnus hos en arbetsgivare",
          "vad vill Magnus ha av en arbetsgivare",
          "vad är viktigt hos en arbetsgivare",
          "ekonomiskt stabil arbetsgivare",
          "expansion",
          "informationsspridning",
          "transparens",
          "öppen kultur",
          "inkluderande kultur",
          "social kultur",
          "vilken typ av arbetsgivare söker Magnus",
          "vad värderar Magnus hos en arbetsgivare",
          "vilken arbetsgivare passar Magnus",
          "vad värderar Magnus på en arbetsplats",
          "vad är viktigt för Magnus på en arbetsplats",
          "vad uppskattar Magnus på en arbetsplats",
        ],
      },
    },
  },
  {
    id: "additional-long-term-career-goals",
    priority: 14,
    translations: {
      en: {
        answer:
          "Long term, what matters most to Magnus is enjoying his work, continuing to develop, and feeling that he contributes to the organization and its development.",
        terms: [
          "long term career goals",
          "career goals",
          "future career",
          "where does Magnus see himself",
          "what are Magnus's long term goals",
          "what does Magnus want long term",
          "future goals",
          "long term goals",
          "what does Magnus want in the long term",
          "where does Magnus want to be in a few years",
        ],
      },
      sv: {
        answer:
          "Det viktigaste för Magnus långsiktigt är att han trivs med sina arbetsuppgifter, fortsätter att utvecklas och känner att han bidrar till verksamheten och dess utveckling.",
        terms: [
          "långsiktiga karriärmål",
          "karriärmål",
          "framtida karriär",
          "var ser Magnus sig själv",
          "vilka är Magnus långsiktiga mål",
          "vad vill Magnus långsiktigt",
          "framtidsmål",
          "mål på lång sikt",
          "vad vill Magnus på lång sikt",
          "var vill Magnus vara om några år",
        ],
      },
    },
  },
  {
    id: "additional-last-role-ended",
    priority: 18,
    translations: {
      en: {
        answer:
          "The board of TH1NG AB (publ), where Magnus worked as Chief Commercial Officer, filed for the company's bankruptcy in June 2025. Magnus really enjoyed working at the company and in his role. At the same time, he tries to see the learning value in having experienced a corporate bankruptcy and the situations and experiences that followed.",
        terms: [
          "why did Magnus leave",
          "why did Magnus leave TH1NG",
          "reason for leaving",
          "TH1NG bankruptcy",
          "bankruptcy",
          "Chief Commercial Officer TH1NG",
          "what happened at TH1NG",
          "what happened to TH1NG",
          "reason Magnus left",
          "why did Magnus employment end",
          "how did Magnus employment end",
        ],
      },
      sv: {
        answer:
          "TH1NG AB (publ), där Magnus arbetade som Chief Commercial Officer, begärdes i konkurs av styrelsen i juni 2025. Magnus trivdes väldigt bra på företaget och i sin roll. Samtidigt försöker han se det lärorika i att ha upplevt en företagskonkurs och de situationer samt erfarenheter som följde därav.",
        terms: [
          "varför slutade Magnus",
          "varför lämnade Magnus TH1NG",
          "varför slutade Magnus på TH1NG",
          "TH1NG konkurs",
          "konkurs",
          "Chief Commercial Officer TH1NG",
          "vad hände på TH1NG",
          "vad hände med TH1NG",
          "orsak till att Magnus slutade",
          "varför upphörde Magnus anställning",
          "hur upphörde Magnus anställning",
        ],
      },
    },
  },
  {
    id: "additional-manager-expectations",
    priority: 14,
    translations: {
      en: {
        answer:
          "Clear expectations, direct communication, and regular follow-up. Beyond that, Magnus values a relationship built on mutual trust.",
        terms: [
          "expects manager",
          "expectations manager",
          "values manager",
          "wants manager",
          "prefers manager",
          "relationship manager",
          "trust manager",
          "direct communication manager",
          "regular follow up manager",
          "what does Magnus expect from his manager",
          "what does Magnus value in a manager",
          "what kind of manager does Magnus prefer",
          "relationship with manager",
        ],
      },
      sv: {
        answer:
          "Tydlighet i förväntningar, rak kommunikation och regelbunden uppföljning. Utöver det värderar Magnus en relation som bygger på tillit och förtroende.",
        terms: [
          "förväntar chef",
          "förväntningar chef",
          "värderar chef",
          "vill ha chef",
          "föredrar chef",
          "relation chef",
          "tillit chef",
          "förtroende chef",
          "rak kommunikation chef",
          "regelbunden uppföljning chef",
          "vad förväntar sig Magnus av sin chef",
          "vad värderar Magnus hos sin chef",
          "vilken typ av chef föredrar Magnus",
          "relation till chef",
        ],
      },
    },
  },
  {
    id: "additional-mistakes-and-setbacks",
    priority: 14,
    translations: {
      en: {
        answer:
          "It depends on the type of mistake. If the mistake is due to carelessness, Magnus is very self-critical. If, however, it is the result of a considered decision between several reasonable alternatives, he also sees it as part of learning and development.",
        terms: [
          "mistakes",
          "handle mistakes",
          "how does Magnus handle mistakes",
          "when things go wrong",
          "failure",
          "wrong decision",
          "bad decision",
          "how does Magnus react to mistakes",
          "what does Magnus do when something goes wrong",
          "how does Magnus handle setbacks",
          "when things do not go as planned",
          "carelessness",
        ],
      },
      sv: {
        answer:
          "Det beror på typ av fel. Om felet beror på slarv är Magnus väldigt självkritisk. Om det däremot är resultatet av ett genomtänkt beslut mellan flera rimliga alternativ, ser han det också som en del av lärandet och utvecklingen.",
        terms: [
          "misstag",
          "hantera misstag",
          "hur hanterar Magnus misstag",
          "när något går fel",
          "när något inte går som planerat",
          "felaktigt beslut",
          "hur reagerar Magnus på misstag",
          "vad gör Magnus när något blir fel",
          "vad gör Magnus när något går fel",
          "hur hanterar Magnus motgångar",
          "när det inte går som planerat",
          "slarv",
        ],
      },
    },
  },
  {
    id: "additional-responsibility-and-mandate",
    priority: 14,
    translations: {
      en: {
        answer:
          "Magnus values having clearly defined responsibility and the mandate to drive issues forward and make decisions. Clearly stated goals, clear expectations, trust, and autonomy with accountability are important factors for Magnus to thrive.",
        terms: [
          "responsibility and mandate",
          "decision authority",
          "what mandate does Magnus prefer",
          "independent responsibility",
          "preferred responsibility",
          "preferred mandate",
          "what mandate does Magnus want",
          "how much authority does Magnus want",
          "clearly defined responsibility and mandate",
          "prefers responsibility",
          "prefer responsibility",
          "wants responsibility",
          "likes responsibility",
          "prefers mandate",
          "wants mandate",
          "level of responsibility Magnus prefers",
          "how much responsibility does Magnus want",
          "autonomy with accountability",
        ],
      },
      sv: {
        answer:
          "Magnus uppskattar ett uttalat ansvar och mandat att driva frågor samt ta beslut. Uttalade mål, tydliga förväntningar, förtroende och frihet under ansvar är viktiga faktorer för att Magnus ska trivas.",
        terms: [
          "ansvar och mandat",
          "ansvarsfördelning",
          "driva egna frågor",
          "föredraget ansvar",
          "föredraget mandat",
          "tydligt ansvar och mandat",
          "trivs med ansvar",
          "trivs bäst med ansvar",
          "föredrar ansvar",
          "vill ha ansvar",
          "trivs med mandat",
          "föredrar mandat",
          "vill ha mandat",
          "hur mycket ansvar vill Magnus ha",
          "hur mycket mandat vill Magnus ha",
          "frihet under ansvar",
        ],
      },
    },
  },
  {
    id: "additional-management-lessons",
    priority: 13,
    translations: {
      en: {
        answer:
          "In his roles as a manager, Magnus has learned that people function differently and have very different needs. He therefore wants to understand his employees well enough to know what each person needs in order to perform and function effectively within the team. Goals, responsibilities, and expectations should be clear, while the way he leads may need to be adapted to the individual and the situation.",
        terms: [
          "management lessons",
          "leadership lessons",
          "what has Magnus learned as a manager",
          "what has Magnus learned from management roles",
          "previous management roles",
          "learned from leadership",
          "employee needs",
          "what has Magnus learned about leadership",
          "what has Magnus learned from being a manager",
          "lessons from management roles",
        ],
      },
      sv: {
        answer:
          "I sina roller som chef har Magnus lärt sig att människor fungerar olika och har väldigt olika behov. Därför vill han förstå sina medarbetare tillräckligt väl för att veta vad som krävs för att respektive person ska prestera och fungera i gruppen. Mål, ansvar och förväntningar ska vara tydliga, medan sättet att leda kan behöva anpassas efter individ och situation.",
        terms: [
          "lärdomar som chef",
          "vad har Magnus lärt sig som chef",
          "vad har Magnus lärt sig av sina chefsroller",
          "tidigare chefsroller",
          "lärdomar från ledarskap",
          "medarbetares behov",
          "vad har Magnus lärt sig om ledarskap",
          "vad har Magnus lärt sig av att vara chef",
          "lärdomar från chefsroller",
        ],
      },
    },
  },
  {
    id: "additional-future-professional-development",
    priority: 14,
    translations: {
      en: {
        answer:
          "To better understand market mechanisms. The market is very fast-moving and dynamic, so it is essential to keep up.",
        terms: [
          "future professional development",
          "professional development",
          "what does Magnus want to improve",
          "what does Magnus want to get better at",
          "what does Magnus want to learn",
          "market mechanisms",
          "understand the market",
          "what does Magnus want to improve professionally",
          "what does Magnus want to develop professionally",
          "professional development goals",
          "what does Magnus want to develop in the coming years",
          "coming years professional development",
        ],
      },
      sv: {
        answer:
          "Att bättre förstå marknadsmekanismerna. Marknaden är väldigt snabbfotad och dynamisk, och ingen vill stå kvar på perrongen.",
        terms: [
          "professionell utveckling",
          "vad vill Magnus bli bättre på",
          "vad vill Magnus utveckla",
          "vad vill Magnus lära sig",
          "marknadsmekanismer",
          "förstå marknaden",
          "kommande åren",
          "vad vill Magnus bli bättre på professionellt",
          "vad vill Magnus utveckla professionellt",
          "professionella utvecklingsmål",
        ],
      },
    },
  },
  {
    id: "additional-new-industry-ramp-up",
    priority: 15,
    translations: {
      en: {
        answer:
          "Quickly. Being able to get up to speed on new issues, understand context, and identify what matters is one of Magnus's clearest strengths. That is also supported by completed logical-reasoning tests.",
        terms: [
          "new industry",
          "new business",
          "new sector",
          "how quickly can Magnus learn a new industry",
          "how quickly can Magnus learn a new business",
          "how quickly can Magnus get up to speed",
          "learn new domain",
          "ramp up",
          "how fast can Magnus learn a new industry",
          "how fast can Magnus learn a new business",
          "how easily can Magnus learn a new industry",
        ],
      },
      sv: {
        answer:
          "Snabbt. Att sätta sig in i nya frågor, förstå sammanhang och identifiera vad som är viktigt är en av Magnus tydligaste styrkor. Det stöds också av genomförda tester av logisk förmåga.",
        terms: [
          "ny bransch",
          "ny verksamhet",
          "hur snabbt kan Magnus sätta sig in i en ny bransch",
          "hur snabbt kan Magnus sätta sig in i en ny verksamhet",
          "sätta sig in i nya frågor",
          "lära sig ny bransch",
          "lära sig ny verksamhet",
          "hur fort kan Magnus sätta sig in i en ny bransch",
          "hur fort kan Magnus sätta sig in i en ny verksamhet",
          "hur lätt lär sig Magnus en ny bransch",
          "hur snabbt lär sig Magnus en ny bransch",
        ],
      },
    },
  },
  {
    id: "additional-colleague-preferences",
    priority: 14,
    translations: {
      en: {
        answer:
          "Magnus values colleagues who are ambitious and work towards established goals, while also being approachable, and sociable. Social interaction is very important to him when it comes to enjoying the workplace, which is why he also places a strong emphasis on honesty and direct communication.",
        terms: [
          "what does Magnus appreciate in colleagues",
          "what does Magnus value in colleagues",
          "what matters to Magnus in colleagues",
          "what does Magnus expect from colleagues",
          "what does Magnus appreciate about coworkers",
          "what does Magnus value in coworkers",
          "what kind of colleagues does Magnus appreciate",
          "relationship with colleagues",
          "ambitious colleagues",
          "social colleagues",
          "honesty with colleagues",
          "direct communication with colleagues",
          "good colleagues",
        ],
      },
      sv: {
        answer:
          "Magnus värderar kollegor som är ambitiösa och arbetar mot uppsatta mål, och som samtidigt har ett trevligt bemötande och är sociala. Det sociala samspelet är väldigt viktigt för trivsel på arbetsplatsen, och därför understryker också Magnus ärlighet och rak kommunikation.",
        terms: [
          "vad uppskattar Magnus hos kollegor",
          "vad värderar Magnus hos kollegor",
          "vad är viktigt för Magnus hos kollegor",
          "vad förväntar sig Magnus av kollegor",
          "vilka kollegor uppskattar Magnus",
          "relation till kollegor",
          "ambitiösa kollegor",
          "sociala kollegor",
          "ärlighet mellan kollegor",
          "rak kommunikation mellan kollegor",
          "bra kollegor",
        ],
      },
    },
  },
  {
    id: "additional-logic-assessment",
    priority: 18,
    translations: {
      en: {
        answer:
          "On Alva Labs' logic test, Magnus scored 9 out of 10, classified as above average and within the 93rd-98th percentile. The test is designed to measure how effectively a person handles complex information and draws correct conclusions from it.",
        terms: [
          "logic test",
          "logical ability",
          "logical reasoning",
          "Alva logic",
          "logic score",
          "9 out of 10",
          "93rd percentile",
          "98th percentile",
          "smart",
          "intelligent",
        ],
      },
      sv: {
        answer:
          "På Alva Labs logiktest fick Magnus 9 av 10, vilket klassificeras som över genomsnittet och motsvarar 93:e-98:e percentilen. Testet mäter hur effektivt man hanterar komplex information och drar korrekta slutsatser från den.",
        terms: [
          "logiktest",
          "logisk förmåga",
          "logiskt resonemang",
          "Alva logik",
          "logikpoäng",
          "9 av 10",
          "93:e percentilen",
          "98:e percentilen",
          "smart",
          "intelligent",
        ],
      },
    },
  },
  {
    id: "additional-personality-assessment-overview",
    priority: 17,
    translations: {
      en: {
        answer:
          "In Alva Labs' Big Five assessment, Magnus scored 6/10 for Agreeableness, 7/10 for Conscientiousness, 7/10 for Extraversion, 8/10 for Emotional Stability, and 7/10 for Openness. The report describes a profile that is persistent, outgoing, resilient, and innovative, while Agreeableness is around the average range.",
        terms: [
          "personality test",
          "personality assessment",
          "Alva personality",
          "Big Five",
          "personality profile",
          "agreeableness conscientiousness extraversion emotional stability openness",
        ],
      },
      sv: {
        answer:
          "I Alva Labs Big Five-test fick Magnus 6/10 i vänlighet, 7/10 i samvetsgrannhet, 7/10 i extraversion, 8/10 i emotionell stabilitet och 7/10 i öppenhet. Rapporten beskriver sammantaget en profil som är ihärdig, utåtriktad, motståndskraftig och innovativ, medan vänlighet ligger omkring genomsnittet.",
        terms: [
          "personlighetstest",
          "personlighetsbedömning",
          "Alva personlighet",
          "Big Five",
          "personlighetsprofil",
          "vänlighet samvetsgrannhet extraversion emotionell stabilitet öppenhet",
        ],
      },
    },
  },
  {
    id: "additional-personality-conscientiousness",
    priority: 15,
    translations: {
      en: {
        answer:
          "Alva Labs places Magnus's Conscientiousness at 7/10, in the 69th-84th percentile. The report describes him as persistent, goal-oriented, hard-working, structured, and organized, with a preference for getting started quickly and completing tasks.",
        terms: [
          "conscientiousness",
          "persistent",
          "organized",
          "structured personality",
          "work discipline",
          "structured",
          "hard-working",
          "goal-oriented",
          "disciplined",
          "conscientious",
          "is Magnus conscientious",
        ],
      },
      sv: {
        answer:
          "Alva Labs placerar Magnus samvetsgrannhet på 7/10, i 69:e-84:e percentilen. Rapporten beskriver honom som ihärdig, målinriktad, hårt arbetande, strukturerad och organiserad, med en tendens att komma igång snabbt och slutföra sina uppgifter.",
        terms: [
          "samvetsgrannhet",
          "ihärdig",
          "målinriktad",
          "ordningsam",
          "strukturerad personlighet",
          "självdisciplin",
          "samvetsgrann",
          "strukturerad",
          "organiserad",
          "hårt arbetande",
          "disciplinerad",
        ],
      },
    },
  },
  {
    id: "additional-personality-extraversion",
    priority: 15,
    translations: {
      en: {
        answer:
          "Alva Labs places Magnus's Extraversion at 7/10, in the 69th-84th percentile. The report describes him as outgoing and social, with particularly high energy at the 84th-93rd percentile. His social-dominance facet is more moderate: he does not always seek the leadership role, but takes it when needed and expresses his view when required.",
        terms: [
          "extraversion",
          "outgoing",
          "social personality",
          "energy level",
          "social dominance",
          "energetic",
          "social",
          "extrovert",
          "extravert",
          "extroverted",
          "extraverted",
          "dominant",
        ],
      },
      sv: {
        answer:
          "Alva Labs placerar Magnus extraversion på 7/10, i 69:e-84:e percentilen. Rapporten beskriver honom som utåtriktad och social, med särskilt hög energinivå i 84:e-93:e percentilen. Social dominans ligger mer i mitten: han söker inte alltid ledarrollen men tar den ibland och uttrycker sin åsikt när det behövs.",
        terms: [
          "extraversion",
          "utåtriktad",
          "social personlighet",
          "energinivå",
          "social dominans",
          "energisk",
          "social",
          "extrovert",
          "extravert",
          "socialt dominant",
          "dominant",
        ],
      },
    },
  },
  {
    id: "additional-personality-emotional-stability",
    priority: 16,
    translations: {
      en: {
        answer:
          "Alva Labs places Magnus's Emotional Stability at 8/10, in the 84th-93rd percentile. The report describes him as resilient and generally calm under pressure, with optimism and stress tolerance also in the 84th-93rd percentile range.",
        terms: [
          "emotional stability",
          "stress tolerance",
          "under pressure",
          "resilience",
          "optimism",
          "calm under pressure",
          "stress-tolerant",
          "stress-resistant",
          "calm",
          "optimistic",
          "emotionally stable",
        ],
      },
      sv: {
        answer:
          "Alva Labs placerar Magnus emotionella stabilitet på 8/10, i 84:e-93:e percentilen. Rapporten beskriver honom som motståndskraftig och generellt lugn under press, med optimism och stresstålighet också i 84:e-93:e percentilen.",
        terms: [
          "emotionell stabilitet",
          "stresstålighet",
          "under press",
          "motståndskraft",
          "optimism",
          "lugn under press",
          "stress",
          "stresstålig",
          "stressresistent",
          "lugn",
          "optimistisk",
          "emotionellt stabil",
        ],
      },
    },
  },
  {
    id: "additional-personality-openness",
    priority: 15,
    translations: {
      en: {
        answer:
          "Alva Labs places Magnus's Openness at 7/10, in the 69th-84th percentile. The report describes him as innovative and intellectually curious, interested in theoretical problems, open to change, and inclined to try new things and contexts.",
        terms: [
          "openness",
          "innovative",
          "curiosity",
          "intellectual curiosity",
          "open to change",
          "change oriented",
          "new things",
          "open-minded",
          "curious",
          "intellectually curious",
          "open to new things",
        ],
      },
      sv: {
        answer:
          "Alva Labs placerar Magnus öppenhet på 7/10, i 69:e-84:e percentilen. Rapporten beskriver honom som innovativ och intellektuellt nyfiken, intresserad av teoretiska problem, öppen för förändring och benägen att prova nya saker och sammanhang.",
        terms: [
          "öppenhet",
          "innovativ",
          "nyfikenhet",
          "intellektuell",
          "intellektuellt nyfiken",
          "öppen för förändring",
          "förändringsbenägen",
          "nya saker",
          "öppen",
          "nyfiken",
          "förändringsöppen",
          "öppen för nya saker",
        ],
      },
    },
  },
  {
    id: "additional-personality-agreeableness",
    priority: 14,
    translations: {
      en: {
        answer:
          "Alva Labs places Magnus's Agreeableness at 6/10, in the 50th-69th percentile. The report describes an average overall level: he can be direct when needed without seeking unnecessary confrontation. Politeness is higher, in the 69th-84th percentile, while trust is around the 50th-69th percentile.",
        terms: [
          "agreeableness",
          "politeness",
          "confrontation",
          "friendly",
          "nice",
          "polite",
          "pleasant",
          "is Magnus friendly",
          "is Magnus nice",
          "is Magnus polite",
          "is Magnus kind",
          "how friendly is Magnus",
          "how polite is Magnus",
          "how trusting is Magnus",
          "trust according to Alva",
          "is Magnus direct",
          "direct personality",
        ],
      },
      sv: {
        answer:
          "Alva Labs placerar Magnus vänlighet på 6/10, i 50:e-69:e percentilen. Rapporten beskriver en genomsnittlig totalnivå: han kan vara rak när det behövs utan att söka onödig konfrontation. Artighet ligger högre, i 69:e-84:e percentilen, medan tillit ligger i 50:e-69:e percentilen.",
        terms: [
          "vänlighet",
          "artighet",
          "konfrontation",
          "vänskaplig",
          "vänlig",
          "trevlig",
          "artig",
          "är Magnus vänlig",
          "är Magnus trevlig",
          "är Magnus artig",
          "hur vänlig är Magnus",
          "hur artig är Magnus",
          "hur tillitsfull är Magnus",
          "tillit enligt Alva",
          "är Magnus rak",
          "rak person",
        ],
      },
    },
  },
  {
    id: "additional-personality-strengths-challenges",
    priority: 15,
    translations: {
      en: {
        answer:
          "Alva Labs highlights three strengths: being decisive and goal-oriented when difficulties arise, spreading enthusiasm while remaining resilient to setbacks, and being highly productive at a fast pace. Potential challenges are forgetting to rest because of high ambition, sometimes underestimating problems through optimism, and occasionally coming across as pushy when he wants things done.",
        terms: [
          "personality strengths",
          "personality challenges",
          "pushy",
          "high ambition",
          "productive",
          "strengths according to Alva",
          "challenges according to Alva",
          "strengths in personality test",
          "challenges in personality test",
          "personality test strengths",
          "personality test challenges",
          "resilience to setbacks",
          "what strengths does Alva show for Magnus",
          "what does Alva say about Magnus strengths",
          "what challenges does Alva show for Magnus",
          "what does Alva say about Magnus challenges",
          "what challenges does the personality test show",
          "what does the personality test say about Magnus strengths",
          "what does the personality test say about Magnus challenges",
        ],
      },
      sv: {
        answer:
          "Alva Labs lyfter tre styrkor: att vara beslutsam och målinriktad när svårigheter uppstår, att sprida entusiasm och vara motståndskraftig mot motgångar samt att vara mycket produktiv i högt tempo. Potentiella utmaningar är att ibland glömma att vila på grund av höga ambitioner, underskatta problem genom optimism och ibland framstå som pådrivande när saker ska bli gjorda.",
        terms: [
          "personlighetsstyrkor",
          "personlighetsutmaningar",
          "pådrivande",
          "höga ambitioner",
          "produktiv",
          "styrkor enligt Alva",
          "utmaningar enligt Alva",
          "styrkor i personlighetstest",
          "utmaningar i personlighetstest",
          "personlighetstestets styrkor",
          "personlighetstestets utmaningar",
          "motståndskraft vid motgångar",
          "vilka styrkor visar Alva för Magnus",
          "vad säger Alva om Magnus styrkor",
          "vilka utmaningar visar Alva för Magnus",
          "vad säger Alva om Magnus utmaningar",
          "vilka utmaningar visar personlighetstestet",
          "vad säger personlighetstestet om Magnus styrkor",
          "vad säger personlighetstestet om Magnus utmaningar",
        ],
      },
    },
  },
  {
    id: "additional-personality-drivers-culture",
    priority: 15,
    translations: {
      en: {
        answer:
          "According to Alva Labs, Magnus's main drivers are stimulation, creativity, and autonomy. The culture preferences highlighted in the report are innovative, energetic, and decisive environments.",
        terms: [
          "drivers",
          "motivational drivers",
          "culture preferences",
          "stimulation",
          "creativity",
          "autonomy",
          "innovative energetic decisive",
          "drivers according to Alva",
          "drivers in personality test",
          "what does Alva say about drivers",
          "what drivers does Alva show",
          "what culture preferences does Magnus have according to Alva",
          "what does the personality test say about Magnus drivers",
        ],
      },
      sv: {
        answer:
          "Enligt Alva Labs är Magnus viktigaste drivande faktorer stimulans, kreativitet och autonomi. Rapporten beskriver hans kulturpreferenser som en arbetskultur präglad av innovation, energi och handlingskraft.",
        terms: [
          "drivande faktorer",
          "motivationsfaktorer",
          "kulturpreferenser",
          "stimulans",
          "kreativitet",
          "autonomi",
          "innovativ energisk beslutsam",
          "drivkrafter enligt Alva",
          "drivkrafter i personlighetstest",
          "vad visar Alva om drivkrafter",
          "vilka drivkrafter visar Alva",
          "vilka kulturpreferenser har Magnus enligt Alva",
          "vad säger personlighetstestet om Magnus drivkrafter",
        ],
      },
    },
  },
  {
    id: "additional-historical-assessment",
    priority: 14,
    translations: {
      en: {
        answer:
          "An earlier competency-development assessment, from 2011, is rather consistent with Magnus's current self-description and newer Alva results. It described a structured and systematic approach, high performance expectations, a tendency to grasp the core of complex problems quickly, effective independent and group work, and a strong drive to get things done. It also noted possible tendencies to underestimate time requirements and to be too forceful at times, which resembles development areas Magnus still recognizes in himself today.",
        terms: [
          "old assessment",
          "older assessment",
          "competency development report",
          "competence development report",
          "historical assessment",
          "assessment over time",
          "tests over time",
          "what did the competency development report say",
          "older test results",
          "does Magnus have older test results",
        ],
      },
      sv: {
        answer:
          "En tidigare kompetensutvecklingsrapport, från 2011, stämmer väl med Magnus nuvarande egenbeskrivning och senare Alva-resultat. Rapporten beskrev ett strukturerat och systematiskt arbetssätt, höga prestationskrav, en förmåga att snabbt se kärnan i komplexa problem, effektivt arbete både självständigt och i grupp samt en stark vilja att få saker gjorda. Den noterade också möjliga tendenser att underskatta tidsåtgång och ibland vara för pådrivande, vilket liknar utvecklingsområden som Magnus fortfarande själv känner igen.",
        terms: [
          "gammal rapport",
          "äldre bedömning",
          "kompetensutvecklingsrapport",
          "historisk bedömning",
          "bedömning över tid",
          "tester över tid",
          "vad stod i kompetensutvecklingsrapporten",
          "äldre testresultat",
          "har Magnus äldre testresultat",
        ],
      },
    },
  },
  {
    id: "additional-contribution-overview",
    priority: 17,
    translations: {
      en: {
        answer:
"Magnus can primarily contribute within the following areas:\n" +
"• Leadership and governance, strategic priorities, and change initiatives.\n" +
"• Business development, growth strategy, pricing strategy, profitability, and sales strategy.\n" +
"• Marketing strategy, positioning, target markets, digital strategy, pipeline generation, data analysis, and structured follow-up.\n" +
"• Web structure, applications, and LLM iteration to support the work.",
        terms: [
          "what can Magnus contribute",
          "how can Magnus contribute",
          "what can Magnus help with",
          "how can Magnus help",
          "what can Magnus assist with",
          "how can Magnus assist",
          "what can Magnus support with",
          "how can Magnus support a company",
          "how can Magnus support a business",
          "where can Magnus add value",
          "what can Magnus bring to a company",
"what can Magnus do for us",
        ],
      },
      sv: {
        answer:
"Magnus kan primärt bidra inom nedan områden:\n" +
"• Ledning och styrning, strategiska prioriteringar och förändringsarbete.\n" +
"• Affärsutveckling, tillväxtstrategi, prisstrategi, lönsamhet och försäljningsstrategi.\n" +
"• Marknadsstrategi, positionering, målmarknader, digital strategi, pipelinegenerering, dataanalys och strukturerad uppföljning.\n" +
"• Webbstruktur, applikationer och LLM-iteration som stöd i arbetet.",
        terms: [
          "vad kan Magnus bidra med",
          "hur kan Magnus bidra",
          "hur bidrar Magnus",
          "vad kan Magnus hjälpa till med",
          "vad kan Magnus hjälpa med",
          "hur kan Magnus hjälpa",
          "vad kan Magnus bistå med",
          "hur kan Magnus bistå",
          "på vilka områden kan Magnus bidra",
          "hur kan Magnus stötta ett företag",
          "hur kan Magnus stötta en verksamhet",
          "vad kan Magnus tillföra",
          "var kan Magnus skapa värde",
"vad kan Magnus göra för oss",
        ],
      },
    },
  },
  {
    id: "additional-contribution-management-governance",
    priority: 18,
    translations: {
      en: {
        answer:
          "Driving change in an organization requires clear direction, effective governance, and responsibility that holds the whole together. Magnus can contribute with strategic priorities, organizational development, change initiatives, and coordination and allocation of responsibilities. The goal is better structure, stronger coordination, and a greater ability to turn decisions into practice.",
        terms: [
          "what can Magnus contribute within management and governance",
          "what can Magnus help with management and governance",
          "what can Magnus assist with management and governance",
          "how can Magnus help with management and governance",
          "can Magnus help with governance",
          "can Magnus assist with governance",
          "can Magnus help with strategic priorities",
          "can Magnus help with organizational development",
          "can Magnus help with organisation development",
          "can Magnus help with change initiatives",
          "can Magnus help with organizational change",
          "can Magnus help with coordination and responsibilities",
          "can Magnus help with allocation of responsibilities",
          "contribute with management and governance",
        ],
      },
      sv: {
        answer:
          "För att driva förändring i en verksamhet krävs tydlig riktning, fungerande styrning och ett ansvar som håller ihop helheten. Magnus kan bidra inom strategiska prioriteringar, organisationsutveckling, förändringsarbete samt samordning och ansvarsfördelning. Målet är bättre struktur, starkare samordning och större förmåga att omsätta beslut i praktiken.",
        terms: [
          "vad kan Magnus bidra med inom ledning och styrning",
          "vad kan Magnus hjälpa till med inom ledning och styrning",
          "vad kan Magnus hjälpa till med ledning och styrning",
          "vad kan Magnus bistå med inom ledning och styrning",
          "hur kan Magnus hjälpa med ledning och styrning",
          "kan Magnus hjälpa med styrning",
          "kan Magnus bistå med styrning",
          "kan Magnus hjälpa med strategiska prioriteringar",
          "kan Magnus hjälpa med organisationsutveckling",
          "kan Magnus hjälpa med förändringsarbete",
          "kan Magnus hjälpa med organisationsförändring",
          "kan Magnus hjälpa med samordning och ansvarsfördelning",
          "kan Magnus hjälpa med ansvarsfördelning",
          "bidra med ledning och styrning",
          "bistå med ledning och styrning",
        ],
      },
    },
  },
  {
    id: "additional-contribution-sales-business-development",
    priority: 18,
    translations: {
      en: {
        answer:
          "Magnus can contribute when sales and business development need clearer commercial direction and sharper priorities. This includes growth strategy and commercial development, sales strategy and commercial priorities, pricing strategy and profitability.",
        terms: [
          "what can Magnus contribute within sales and business development",
          "what can Magnus help with sales and business development",
          "what can Magnus assist with sales and business development",
          "how can Magnus help with sales and business development",
          "can Magnus help with sales",
          "can Magnus help with business development",
          "can Magnus assist with business development",
          "can Magnus help with growth strategy",
          "can Magnus help with commercial development",
          "can Magnus help with sales strategy",
          "can Magnus help with commercial priorities",
          "can Magnus help with pricing strategy",
          "can Magnus help with profitability",
          "can Magnus help with business models",
          "contribute with sales and business development",
          "assist with sales and business development",
        ],
      },
      sv: {
        answer:
          "Magnus kan bidra när försäljning och affärsutveckling behöver en tydligare kommersiell riktning och skarpare prioriteringar. Det omfattar tillväxtstrategi och kommersiell utveckling, försäljningsstrategi och kommersiella prioriteringar, prisstrategi och lönsamhet.",
        terms: [
          "vad kan Magnus bidra med inom försäljning och affärsutveckling",
          "vad kan Magnus hjälpa till med inom försäljning och affärsutveckling",
          "vad kan Magnus hjälpa till med försäljning och affärsutveckling",
          "vad kan Magnus bistå med inom försäljning och affärsutveckling",
          "hur kan Magnus hjälpa med försäljning och affärsutveckling",
          "kan Magnus hjälpa med försäljning",
          "kan Magnus hjälpa med affärsutveckling",
          "kan Magnus bistå med affärsutveckling",
          "kan Magnus hjälpa med tillväxtstrategi",
          "kan Magnus hjälpa med kommersiell utveckling",
          "kan Magnus hjälpa med försäljningsstrategi",
          "kan Magnus hjälpa med kommersiella prioriteringar",
          "kan Magnus hjälpa med prisstrategi",
          "kan Magnus hjälpa med lönsamhet",
          "kan Magnus hjälpa med affärsmodeller",
          "bidra med försäljning och affärsutveckling",
          "bistå med försäljning och affärsutveckling",
        ],
      },
    },
  },
  {
    id: "additional-contribution-marketing-communication-digital",
    priority: 18,
    translations: {
      en: {
        answer:
          "Magnus can contribute when marketing and communication need clearer focus, stronger positioning, and a more relevant digital presence. This includes marketing strategy, target market and positioning, content and communication, and digital strategy.",
        terms: [
          "what can Magnus contribute within marketing communication and digital presence",
          "what can Magnus help with marketing communication and digital presence",
          "what can Magnus assist with marketing communication and digital presence",
          "how can Magnus help with marketing and communication",
          "can Magnus help with marketing strategy",
          "can Magnus help with communication",
          "can Magnus help with content and communication",
          "can Magnus help with target market",
          "can Magnus help with positioning",
          "can Magnus help with digital strategy",
          "can Magnus help with digital presence",
          "contribute with marketing communication and digital presence",
        ],
      },
      sv: {
        answer:
          "Magnus kan bidra när marknad och kommunikation behöver tydligare fokus, starkare positionering och en mer relevant digital närvaro. Det omfattar marknadsstrategi, målmarknad och positionering, innehåll och kommunikation samt digital strategi.",
        terms: [
          "vad kan Magnus bidra med inom marknad kommunikation och digital närvaro",
          "vad kan Magnus hjälpa till med inom marknad kommunikation och digital närvaro",
          "vad kan Magnus hjälpa till med marknad kommunikation och digital närvaro",
          "vad kan Magnus bistå med inom marknad kommunikation och digital närvaro",
          "hur kan Magnus hjälpa med marknad och kommunikation",
          "kan Magnus hjälpa med marknadsstrategi",
          "kan Magnus hjälpa med kommunikation",
          "kan Magnus hjälpa med innehåll och kommunikation",
          "kan Magnus hjälpa med målmarknad",
          "kan Magnus hjälpa med positionering",
          "kan Magnus hjälpa med digital strategi",
          "kan Magnus hjälpa med digital närvaro",
          "bidra med marknad kommunikation och digital närvaro",
        ],
      },
    },
  },
  {
    id: "additional-contribution-web-content-ai",
    priority: 18,
    translations: {
      en: {
        answer:
          "Magnus can contribute to the structure and refinement of websites and applications, with a focus on clear information architecture, coherent content, and visual presentation. He also uses LLM iteration as a practical support in the work.",
        terms: [
  "what can Magnus contribute within web structure content and AI support",
  "what can Magnus help with web structure content and AI support",
  "what can Magnus assist with web structure content and AI support",
  "how can Magnus help with web structure",
  "can Magnus help with web structure",
  "can Magnus help with website structure",
  "can Magnus help with websites",
  "can Magnus help with applications",
  "can Magnus help with information architecture",
  "can Magnus help with content structure",
  "can Magnus help with web content",
  "can Magnus help with visual presentation",
  "can Magnus help with LLM iteration",
  "can Magnus help with AI support",
  "can Magnus help with SEO",
  "can Magnus help with GEO",
  "contribute to web structure content and AI support",
        ],
      },
      sv: {
        answer:
          "Magnus kan bidra med struktur och utveckling av webbsidor och applikationer, med fokus på tydlig informationsstruktur, sammanhållet innehåll och visuell presentation. Han använder även LLM-iteration som ett praktiskt stöd i arbetet.",
        terms: [
  "vad kan Magnus bidra med inom webbstruktur innehåll och AI-stöd",
  "vad kan Magnus hjälpa till med inom webbstruktur innehåll och AI-stöd",
  "vad kan Magnus hjälpa till med webbstruktur innehåll och AI-stöd",
  "vad kan Magnus bistå med inom webbstruktur innehåll och AI-stöd",
  "hur kan Magnus hjälpa med webbstruktur",
  "kan Magnus hjälpa med webbstruktur",
  "kan Magnus hjälpa med webbplatsstruktur",
  "kan Magnus hjälpa med webbsidor",
  "kan Magnus hjälpa med applikationer",
  "kan Magnus hjälpa med informationsstruktur",
  "kan Magnus hjälpa med innehållsstruktur",
  "kan Magnus hjälpa med webbinnehåll",
  "kan Magnus hjälpa med visuell presentation",
  "kan Magnus hjälpa med LLM-iteration",
  "kan Magnus hjälpa med AI-stöd",
  "kan Magnus hjälpa med SEO",
  "kan Magnus hjälpa med GEO",
  "bidra med webbstruktur innehåll och AI-stöd",
        ],
      },
    },
  },
];

// Transformerar källkoden till det förväntade Record<SiteLanguage, ChatKnowledgeItem[]>-formatet
export const additionalChatKnowledge: Record<
  SiteLanguage,
  readonly ChatKnowledgeItem[]
> = {
  en: rawKnowledgeEntries.map((entry) => ({
    id: entry.id,
    priority: entry.priority,
    answer: entry.translations.en.answer,
    terms: entry.translations.en.terms,
  })),
  sv: rawKnowledgeEntries.map((entry) => ({
    id: entry.id,
    priority: entry.priority,
    answer: entry.translations.sv.answer,
    terms: entry.translations.sv.terms,
  })),
};