// lib/chatbot/additionalKnowledge.ts

import type { SiteLanguage } from "@/lib/content/profile";
import type { ChatKnowledgeItem } from "@/lib/chatbot/types";

export const additionalChatKnowledge: Record<
  SiteLanguage,
  readonly ChatKnowledgeItem[]
> = {
  en: [
    {
      id: "additional-next-role",
      answer:
        "Magnus is searching broadly, primarily for roles in project management, business development, and commercial leadership. He is most interested in commercial contexts where the business or operations have development potential. The opportunity to develop, contribute, and work in a healthy environment with sound people practices matters more to him than the exact functional label.",
      terms: [
        "next role",
        "roles Magnus is looking for",
        "what roles is Magnus looking for",
        "what job is Magnus looking for",
        "what does Magnus want to work with",
        "what does Magnus want to work on",
        "what kind of role does Magnus want",
        "what does Magnus want to do next",
        "career interests",
        "job interests",
        "project management role",
        "business development role",
        "commercial leadership role",
        "commercial roles",
      ],
      priority: 12,
    },
    {
      id: "additional-leadership-style",
      answer:
        "Magnus describes his leadership style as attentive and trust-based. He listens to the people around him, tries to understand different perspectives, and tends to build trust. He sees that trust as an important basis for engagement and for people to have confidence in what he communicates.",
      terms: [
        "leadership style",
        "how does Magnus lead",
        "leadership",
        "engagement",
        "build trust",
        "trust based leadership",
        "people leadership",
      ],
      priority: 11,
    },
    {
      id: "additional-formal-people-management",
      answer:
        "Magnus has held formal people-management responsibility as Marketing Manager and acting CEO at Bahnhof Unipessoal Lda, and as Chief Commercial Officer at TH1NG AB.",
      terms: [
        "formal people management",
        "people management responsibility",
        "personnel responsibility",
        "staff responsibility",
        "line management",
        "direct reports",
        "managed employees",
        "Bahnhof Unipessoal",
        "acting CEO",
      ],
      priority: 14,
    },
    {
      id: "additional-resistance-and-difficult-decisions",
      answer:
        "When Magnus meets resistance, he tries different angles and checks his reasoning with people who have stronger experience in the relevant area. Difficult decisions depend on the situation, but when a decision is required to deliver on an assignment, he tries to stay factual and focus on the task, the conditions, and what needs to be delivered rather than making the decision overly emotional.",
      terms: [
        "handle resistance",
        "dealing with resistance",
        "difficult decisions",
        "hard decisions",
        "decision making under pressure",
        "conflict",
      ],
      priority: 10,
    },
    {
      id: "additional-project-management-approach",
      answer:
        "When Magnus takes responsibility for a new project, he first gets a firm understanding of the assignment and its premises. He then builds the outline of a project and timeline plan and keeps iterating it to make delivery and timing as realistic as possible. He prefers to structure what can be structured in an overall plan, work from it continuously, and revise it when conditions change rather than create expectations that cannot be met.",
      terms: [
        "project management approach",
        "how does Magnus manage projects",
        "how does Magnus run projects",
        "new project",
        "project plan",
        "project planning",
        "timeline planning",
        "project structure",
        "project follow up",
      ],
      priority: 14,
    },
    {
      id: "additional-strategy-execution-strength",
      answer:
        "Magnus does not describe himself as strongest in one isolated phase such as strategy formulation or follow-up. His main strength is getting hold of a task, understanding it, and starting the work. Within that process, analysis and structuring come naturally to him, but he sees initiative and forward movement as the more defining strength.",
      terms: [
        "strategy execution",
        "analysis or execution",
        "analysis strength",
        "structuring",
        "execution strength",
        "getting started",
        "initiative",
        "strategic execution",
      ],
      priority: 11,
    },
    {
      id: "additional-change-environments",
      answer:
        "Magnus has worked in changing environments for much of his career, so he tends to treat change as part of the normal working context rather than as something exceptional. Change can require more effort, but he focuses primarily on what the situation requires and what needs to be done.",
      terms: [
        "change",
        "change management",
        "changing environment",
        "transformation",
        "organizational change",
        "working with change",
      ],
      priority: 10,
    },
    {
      id: "additional-commercial-strengths",
      answer:
        "Within commercial work, Magnus sees business development, pricing, and commercial agreements as particularly strong areas. He especially enjoys creating or developing agreements that fit the needs of a specific business or commercial situation.",
      terms: [
        "commercial strengths",
        "business development",
        "pricing",
        "pricing strategy",
        "commercial agreements",
        "contracts",
        "contract development",
        "strongest commercial areas",
      ],
      priority: 14,
    },
    {
      id: "additional-cross-functional-collaboration",
      answer:
        "When functions or stakeholders have different objectives, Magnus first looks at the situation and which objective is overriding. He tries to understand why the views differ, iterate toward a workable solution, and zoom out to the overall business perspective rather than stay locked in a functional view. If he has a clear assignment and target to deliver, he needs a substantive reason before compromising on that target.",
      terms: [
        "cross functional collaboration",
        "stakeholder disagreement",
        "different objectives",
        "conflicting goals",
        "stakeholder management",
        "collaboration",
        "cross functional",
      ],
      priority: 12,
    },
    {
      id: "additional-preferred-work-environment",
      answer:
        "Magnus tends to perform best in smaller organizations where individuals carry substantial responsibility and have room to step forward and influence outcomes. He appreciates shorter decision paths and fewer bureaucratic layers. At the same time, he recognizes the advantages of larger organizations, particularly established central functions and greater financial stability.",
      terms: [
        "work environment",
        "preferred organization",
        "company size",
        "small company",
        "large company",
        "organizational culture",
        "workplace culture",
        "best environment",
      ],
      priority: 12,
    },
    {
      id: "additional-working-style",
      answer:
        "Magnus prefers a combination of independent responsibility and teamwork. He often performs better when he can work independently on issues that benefit from concentrated ownership, while other questions need broader context and multiple perspectives. He also values the social exchange that comes from working with a team.",
      terms: [
        "working style",
        "independent or team",
        "teamwork",
        "independent work",
        "self directed",
        "team collaboration",
        "how does Magnus work",
      ],
      priority: 11,
    },
    {
      id: "additional-problem-solving",
      answer:
        "Magnus approaches complex or unclear problems by pressure-testing them from different directions. He rarely locks himself into one line of thought; when he gets stuck, he steps back and looks at the question from additional perspectives before deciding how to proceed.",
      terms: [
        "problem solving",
        "complex problem",
        "unclear problem",
        "ambiguous problem",
        "pressure test",
        "solve problems",
        "different perspectives",
      ],
      priority: 13,
    },
    {
      id: "additional-motivation",
      answer:
        "Magnus is particularly motivated by developing, receiving recognition for good work, and broadening the scope of his responsibilities. Motivation drops when those elements are missing and when work is repeatedly disrupted by unprioritized issues coming in from the side.",
      terms: [
        "motivation",
        "what motivates Magnus",
        "motivated at work",
        "demotivates",
        "loses motivation",
        "job enlargement",
        "recognition",
      ],
      priority: 12,
    },
    {
      id: "additional-self-described-strengths",
      answer:
        "Magnus would highlight initiative, learning quickly, decisiveness, a high work pace, and social ability as five of his professional strengths.",
      terms: [
        "self described strengths",
        "professional strengths",
        "Magnus strengths",
        "initiative",
        "quick learner",
        "decisive",
        "high work pace",
        "social ability",
      ],
      priority: 12,
    },
    {
      id: "additional-development-areas",
      answer:
        "Magnus sees two practical development areas in himself. First being better at recognizing when other people will not deliver as expected, and second is planning his own time with more margin. He always meets deadlines, but acknowledges that his time planning can make the final phase unnecessarily stressful.",
      terms: [
        "development areas",
        "weaknesses",
        "areas to improve",
        "what can Magnus improve",
        "time planning",
        "time management",
        "deadlines",
      ],
      priority: 13,
    },
    {
      id: "additional-industry-openness",
      answer:
        "Magnus is open to industries beyond telecom, IT, and IoT. He has specifically identified energy and defence as sectors he would be interested in, but he is not limiting himself to those.",
      terms: [
        "industry",
        "industries",
        "other industries",
        "energy sector",
        "defence sector",
        "defense sector",
        "telecom industry",
        "industry preference",
      ],
      priority: 12,
    },
    {
      id: "additional-location-flexibility",
      answer:
        "Stockholm is Magnus's base and he is not highly relocatable. He can work on site in other locations during odd-numbered weeks, while alternate weeks require him to remain in Stockholm. Within those constraints he is broadly flexible about location and travel.",
      terms: [
        "location flexibility",
        "relocate",
        "relocation",
        "work in another city",
        "work elsewhere",
        "travel for work",
        "Stockholm base",
        "odd weeks",
      ],
      priority: 15,
    },
    {
      id: "additional-hybrid-remote",
      answer:
        "Magnus prefers a hybrid setup with a mix of office presence and remote work. He feels that fully remote work can reduce context, community, and useful synergies between colleagues, although he remains open to different arrangements rather than setting rigid rules.",
      terms: [
        "hybrid",
        "remote",
        "remote work",
        "office",
        "work from home",
        "working arrangement",
        "hybrid work",
      ],
      priority: 13,
    },
    {
      id: "additional-availability",
      answer: "Magnus is available to start immediately.",
      terms: [
        "availability",
        "available to start",
        "when can Magnus start",
        "start date",
        "notice period",
        "immediately available",
      ],
      priority: 18,
    },
    {
      id: "additional-languages-practical",
      answer:
        "Magnus speaks Swedish natively and English professionally. His German is limited, although he understands a fair amount. His Spanish and Portuguese are very limited and do not add professional working capability.",
      terms: [
        "languages",
        "English professionally",
        "professional English",
        "can Magnus work in English",
        "German",
        "Spanish",
        "Portuguese",
        "language skills",
      ],
      priority: 14,
    },
    {
      id: "additional-favorite-color",
      answer: "Magnus's favorite color is purple.",
      terms: [
        "favorite color",
        "favourite colour",
        "favorite colour",
        "what color does Magnus like",
        "purple",
      ],
      priority: 18,
    },
    {
      id: "additional-interests",
      answer:
        "Outside work, Magnus mainly trains at the gym and runs. In winter he skis downhill and cross-country. He listens to a lot of popular music but has a particular liking for trance and hard rock, and he plays some guitar although less than before. He also practices card magic and card illusions, which he finds both fun and challenging.",
      terms: [
        "interests",
        "hobbies",
        "free time",
        "outside work",
        "gym",
        "running",
        "skiing",
        "cross country skiing",
        "music",
        "trance",
        "hard rock",
        "guitar",
        "card magic",
        "card tricks",
        "card illusions",
      ],
      priority: 12,
    },
    {
      id: "additional-personality-outside-work",
      answer:
        "Magnus thinks people who know him well would describe him as social, pleasant, and someone they can trust. They would probably also call him a time optimist who can arrive a little later than agreed in private settings.",
      terms: [
        "personality outside work",
        "what is Magnus like personally",
        "friends describe Magnus",
        "what would others say about Magnus",
        "how would others describe Magnus",
        "how would people who know Magnus describe him",
        "social",
        "trustworthy",
        "time optimist",
        "late",
      ],
      priority: 11,
    },
    {
      id: "additional-parachute-ranger-impact",
      answer:
        "Magnus believes his parachute-ranger service taught him that people can handle considerably more than they initially think. He sees that experience as one reason it takes a great deal for him to give up when something is difficult.",
      terms: [
        "parachute ranger",
        "military service",
        "military background",
        "ranger service",
        "resilience",
        "giving up",
      ],
      priority: 13,
    },
    {
      id: "additional-career-breadth",
      answer:
        "Magnus deliberately built breadth across sales, business development, strategy, marketing, legal and regulatory work, and projects because he values job enlargement. He has generally enjoyed roles most when he can combine several areas rather than focus on only one narrow function.",
      terms: [
        "career choices",
        "career breadth",
        "why different roles",
        "sales business development strategy marketing",
        "legal regulatory",
        "broad experience",
        "job enlargement",
      ],
      priority: 13,
    },
    {
      id: "additional-differentiator",
      answer:
        "Magnus sees his ability to understand new subjects quickly, take hold of the work, and produce at a high pace as a key differentiator. At the same time, he does not want work to become so all-consuming that relationships disappear from view; even under a high workload he tries to remain social, available, and give colleagues time and attention.",
      terms: [
        "what makes Magnus different",
        "different from other candidates",
        "differentiator",
        "why hire Magnus",
        "unique strength",
        "candidate comparison",
      ],
      priority: 16,
    },
    {
      id: "additional-logic-assessment",
      answer:
        "On Alva Labs' logic test, Magnus scored 9 out of 10, classified as above average and within the 93rd-98th percentile. The test is designed to measure how effectively a person handles complex information and draws correct conclusions from it.",
      terms: [
        "logic test",
        "logical ability",
        "logical reasoning",
        "Alva logic",
        "logic score",
        "9 out of 10",
        "93rd percentile",
        "98th percentile",
      ],
      priority: 18,
    },
    {
      id: "additional-personality-assessment-overview",
      answer:
        "In Alva Labs' Big Five assessment, Magnus scored 6/10 for Agreeableness, 7/10 for Conscientiousness, 7/10 for Extraversion, 8/10 for Emotional Stability, and 7/10 for Openness. The report describes a profile that is persistent, outgoing, resilient, and innovative, while Agreeableness is around the average range.",
      terms: [
        "personality test",
        "personality assessment",
        "Alva personality",
        "Big Five",
        "personality profile",
        "agreeableness conscientiousness extraversion emotional stability openness",
      ],
      priority: 17,
    },
    {
      id: "additional-personality-conscientiousness",
      answer:
        "Alva Labs places Magnus's Conscientiousness at 7/10, in the 69th-84th percentile. The report describes him as persistent, goal-oriented, hard-working, structured, and organized, with a preference for getting started quickly and completing tasks.",
      terms: [
        "conscientiousness",
        "persistent",
        "goal oriented",
        "organized",
        "structured personality",
        "work discipline",
      ],
      priority: 15,
    },
    {
      id: "additional-personality-extraversion",
      answer:
        "Alva Labs places Magnus's Extraversion at 7/10, in the 69th-84th percentile. The report describes him as outgoing and social, with particularly high energy at the 84th-93rd percentile. His social-dominance facet is more moderate: he does not always seek the leadership role, but takes it when needed and expresses his view when required.",
      terms: [
        "extraversion",
        "outgoing",
        "social personality",
        "energy level",
        "social dominance",
        "energetic",
      ],
      priority: 15,
    },
    {
      id: "additional-personality-emotional-stability",
      answer:
        "Alva Labs places Magnus's Emotional Stability at 8/10, in the 84th-93rd percentile. The report describes him as resilient and generally calm under pressure, with optimism and stress tolerance also in the 84th-93rd percentile range.",
      terms: [
        "emotional stability",
        "stress tolerance",
        "under pressure",
        "resilience",
        "optimism",
        "calm under pressure",
        "stress resistant",
      ],
      priority: 16,
    },
    {
      id: "additional-personality-openness",
      answer:
        "Alva Labs places Magnus's Openness at 7/10, in the 69th-84th percentile. The report describes him as innovative and intellectually curious, interested in theoretical problems, open to change, and inclined to try new things and contexts.",
      terms: [
        "openness",
        "innovative",
        "curiosity",
        "intellectual curiosity",
        "open to change",
        "change oriented",
        "new things",
      ],
      priority: 15,
    },
    {
      id: "additional-personality-agreeableness",
      answer:
        "Alva Labs places Magnus's Agreeableness at 6/10, in the 50th-69th percentile. The report describes an average overall level: he can be direct when needed without seeking unnecessary confrontation. Politeness is higher, in the 69th-84th percentile, while trust is around the 50th-69th percentile.",
      terms: [
        "agreeableness",
        "politeness",
        "trust",
        "direct",
        "confrontation",
        "friendly",
      ],
      priority: 14,
    },
    {
      id: "additional-personality-strengths-challenges",
      answer:
        "Alva Labs highlights three potential strengths: being decisive and goal-oriented when difficulties arise, spreading enthusiasm while remaining resilient to setbacks, and being highly productive at a fast pace. Potential challenges are forgetting to rest because of high ambition, sometimes underestimating problems through optimism, and occasionally coming across as pushy when he wants things done.",
      terms: [
        "personality strengths",
        "personality challenges",
        "Alva strengths",
        "Alva challenges",
        "pushy",
        "high ambition",
        "productive",
        "setbacks",
      ],
      priority: 15,
    },
    {
      id: "additional-personality-drivers-culture",
      answer:
        "According to Alva Labs, Magnus's main drivers are stimulation, creativity, and autonomy. The culture preferences highlighted in the report are innovative, energetic, and decisive environments.",
      terms: [
        "drivers",
        "motivational drivers",
        "culture preferences",
        "stimulation",
        "creativity",
        "autonomy",
        "innovative energetic decisive",
      ],
      priority: 15,
    },
    {
      id: "additional-historical-assessment",
      answer:
        "A 2011 competency-development assessment is older and should not be treated as a current standalone description, but several themes are consistent with Magnus's current self-description and newer Alva results. It described a structured and systematic approach, high performance expectations, a tendency to grasp the core of complex problems quickly, effective independent and group work, and a strong drive to get things done. It also noted possible tendencies to underestimate time requirements and to be too forceful at times, which resembles development areas Magnus still recognizes in himself today.",
      terms: [
        "2011 assessment",
        "old assessment",
        "older assessment",
        "competency development report",
        "competence development report",
        "historical assessment",
        "assessment over time",
        "tests over time",
      ],
      priority: 14,
    },
  ],
  sv: [
    {
      id: "additional-next-role",
      answer:
        "Magnus söker ganska brett, framför allt roller inom projektledning, affärsutveckling och kommersiell ledning. Mest intressanta är roller i en kommersiell kontext där affären och/eller verksamheten har utvecklingspotential. Möjligheten att utvecklas, bidra till verksamheten och arbeta i en bra arbetsmiljö med en sund personalpolitik är viktigare än den exakta funktionsrubriken.",
      terms: [
        "nästa roll",
        "vilka roller söker Magnus",
        "vad söker Magnus för jobb",
        "vad vill Magnus arbeta med",
        "vad vill Magnus jobba med",
        "vilken typ av roll vill Magnus ha",
        "vad vill Magnus göra härnäst",
        "karriärintressen",
        "jobbsök",
        "projektledningsroll",
        "affärsutvecklingsroll",
        "kommersiell ledning",
        "kommersiella roller",
      ],
      priority: 12,
    },
    {
      id: "additional-leadership-style",
      answer:
        "Magnus beskriver sitt ledarskap som lyhört och förtroendeskapande. Han lyssnar på sin omgivning, försöker förstå olika perspektiv och har lätt för att skapa förtroende. Han ser den tilliten som en viktig grund för engagemang och för att medarbetare ska känna förtroende för det han förmedlar.",
      terms: [
        "ledarskapsstil",
        "hur leder Magnus",
        "ledarskap",
        "engagemang",
        "skapa förtroende",
        "tillit",
        "personalledning",
      ],
      priority: 11,
    },
    {
      id: "additional-formal-people-management",
      answer:
        "Magnus har haft formellt personalansvar som marknadschef och tillförordnad VD på Bahnhof Unipessoal Lda samt som Chief Commercial Officer på TH1NG AB.",
      terms: [
        "formellt personalansvar",
        "personalansvar",
        "chefserfarenhet",
        "linjechef",
        "direktrapporterande",
        "lett personal",
        "Bahnhof Unipessoal",
        "tillförordnad vd",
        "tf vd",
      ],
      priority: 14,
    },
    {
      id: "additional-resistance-and-difficult-decisions",
      answer:
        "När Magnus möter motstånd försöker han angripa frågan från olika håll och stämmer gärna av med personer som har större erfarenhet inom det aktuella området. Svåra beslut beror på situationen, men när ett beslut krävs för att leverera på ett uppdrag försöker han förhålla sig sakligt till uppgiften, förutsättningarna och det som behöver levereras snarare än att göra beslutet mer känslomässigt än nödvändigt.",
      terms: [
        "hantera motstånd",
        "motstånd",
        "svåra beslut",
        "jobbiga beslut",
        "beslutsfattande under press",
        "konflikt",
      ],
      priority: 10,
    },
    {
      id: "additional-project-management-approach",
      answer:
        "När Magnus får ansvar för ett nytt projekt börjar han med att sätta sig in i uppgiften och de premisser som gäller. Därefter tar han fram ett övergripande skal till projekt- och tidsplan och itererar löpande för att göra leverans och tidsåtgång så realistiska som möjligt. Han försöker strukturera det som går att strukturera i en övergripande plan, arbeta utifrån den och revidera när förutsättningarna förändras, i stället för att skapa förväntningar som inte går att uppfylla.",
      terms: [
        "projektledning",
        "hur arbetar Magnus med projektledning",
        "hur driver Magnus projekt",
        "nytt projekt",
        "projektplan",
        "projektplanering",
        "tidsplan",
        "projektstruktur",
        "projektuppföljning",
      ],
      priority: 14,
    },
    {
      id: "additional-strategy-execution-strength",
      answer:
        "Magnus beskriver inte sig själv som starkast i en isolerad del som strategiformulering eller uppföljning. Hans främsta styrka är snarare att ta tag i en uppgift, sätta sig in i den och påbörja arbetet. Inom det arbetet kommer analys och strukturering naturligt, men han ser initiativförmåga och framåtrörelse som mer utmärkande styrkor.",
      terms: [
        "strategigenomförande",
        "strategiexekvering",
        "analys eller genomförande",
        "analysstyrka",
        "strukturering",
        "genomförande",
        "komma igång",
        "initiativ",
      ],
      priority: 11,
    },
    {
      id: "additional-change-environments",
      answer:
        "Magnus har arbetat i föränderliga miljöer under stora delar av karriären och betraktar därför förändring mer som en normal del av arbetskontexten än som något exceptionellt. Förändring kan kräva mer energi, men han fokuserar framför allt på vad situationen kräver och vad som behöver göras.",
      terms: [
        "förändring",
        "förändringsledning",
        "föränderlig miljö",
        "transformation",
        "organisationsförändring",
        "arbeta med förändring",
      ],
      priority: 10,
    },
    {
      id: "additional-commercial-strengths",
      answer:
        "Inom det kommersiella området ser Magnus affärsutveckling, prissättning och kommersiella avtal som särskilt starka områden. Han tycker särskilt om att skapa eller utveckla avtal som är anpassade efter en viss verksamhet eller affär.",
      terms: [
        "kommersiella styrkor",
        "affärsutveckling",
        "prissättning",
        "prisstrategi",
        "kommersiella avtal",
        "avtal",
        "avtalsutveckling",
        "starkaste kommersiella områden",
      ],
      priority: 14,
    },
    {
      id: "additional-cross-functional-collaboration",
      answer:
        "När funktioner eller intressenter har olika mål utgår Magnus först från situationen och vilken fråga som är överordnad. Han försöker förstå varför uppfattningarna skiljer sig, iterera mot en fungerande lösning och zooma ut till ett helhetsperspektiv i stället för att låsa sig vid ett funktionellt perspektiv. Om han har ett tydligt uppdrag och mål att leverera på krävs det ett substantiellt skäl för att han ska kompromissa med det målet.",
      terms: [
        "tvärfunktionellt samarbete",
        "intressenter oense",
        "olika mål",
        "motstridiga mål",
        "intressenthantering",
        "samarbete",
        "tvärfunktionellt",
      ],
      priority: 12,
    },
    {
      id: "additional-preferred-work-environment",
      answer:
        "Magnus kommer generellt bäst till sin rätt i mindre organisationer där den enskilde har stort ansvar och möjlighet att kliva fram och påverka. Han uppskattar kortare beslutsvägar och färre byråkratiska lager. Samtidigt ser han fördelarna med större organisationer, framför allt etablerade centrala funktioner och större ekonomisk stabilitet.",
      terms: [
        "arbetsmiljö",
        "vilken organisation passar Magnus",
        "företagsstorlek",
        "mindre organisation",
        "större organisation",
        "organisationskultur",
        "företagskultur",
        "bästa arbetsmiljö",
      ],
      priority: 12,
    },
    {
      id: "additional-working-style",
      answer:
        "Magnus föredrar en kombination av självständigt ansvar och teamsamarbete. Han levererar ofta bättre när han kan arbeta självständigt med frågor som gynnas av koncentrerat ansvar, medan andra frågor kräver större sammanhang och flera perspektiv. Han uppskattar också det sociala utbyte som kommer av att arbeta i grupp.",
      terms: [
        "arbetssätt",
        "självständigt eller team",
        "teamarbete",
        "självständigt arbete",
        "eget ansvar",
        "grupparbete",
        "hur arbetar Magnus",
      ],
      priority: 11,
    },
    {
      id: "additional-problem-solving",
      answer:
        "Magnus angriper komplexa eller otydliga problem genom att trycktesta dem från olika håll. Han låser sällan fast sig i ett tankesätt; när han kör fast backar han tillbaka och betraktar frågan ur fler perspektiv innan han bestämmer hur han ska gå vidare.",
      terms: [
        "problemlösning",
        "komplext problem",
        "otydligt problem",
        "oklar uppgift",
        "trycktesta",
        "lösa problem",
        "olika perspektiv",
      ],
      priority: 13,
    },
    {
      id: "additional-motivation",
      answer:
        "Magnus motiveras särskilt av att utvecklas, få uppskattning för ett bra arbete och bredda sitt ansvar. Motivationen minskar när de delarna saknas och när arbetet återkommande störs av oprioriterade frågor som kommer in från sidan.",
      terms: [
        "motivation",
        "vad motiverar Magnus",
        "motiverad på jobbet",
        "demotiverar",
        "tappar motivation",
        "arbetsvidgning",
        "uppskattning",
      ],
      priority: 12,
    },
    {
      id: "additional-self-described-strengths",
      answer:
        "Magnus skulle själv lyfta fram initiativförmåga, att han är lättlärd, beslutsam, har ett högt arbetstempo och är social som fem professionella styrkor.",
      terms: [
        "egna styrkor",
        "professionella styrkor",
        "Magnus styrkor",
        "initiativtagande",
        "lättlärd",
        "beslutsam",
        "högt arbetstempo",
        "social",
      ],
      priority: 12,
    },
    {
      id: "additional-development-areas",
      answer:
        "Magnus ser två praktiska utvecklingsområden hos sig själv. Först bli bättre på att förstå när andra inte kommer att leverera som förväntat, och sedan att planera sin egen tid med större marginal. Han håller sina deadlines, men konstaterar att tidsplaneringen ibland kan göra slutskedet onödigt stressigt.",
      terms: [
        "utvecklingsområden",
        "svagheter",
        "förbättringsområden",
        "vad kan Magnus förbättra",
        "tidsplanering",
        "tidshantering",
        "deadlines",
      ],
      priority: 13,
    },
    {
      id: "additional-industry-openness",
      answer:
        "Magnus är öppen för andra branscher än telekom, IT och IoT. Han har särskilt nämnt energisektorn och försvarssektorn som intressanta, men begränsar sig inte till dem.",
      terms: [
        "bransch",
        "branscher",
        "andra branscher",
        "energisektorn",
        "försvarssektorn",
        "telekombranschen",
        "branschpreferens",
      ],
      priority: 12,
    },
    {
      id: "additional-location-flexibility",
      answer:
        "Stockholm är Magnus bas och han är inte särskilt flyttbar. Under ojämna veckor kan han arbeta på plats på annan ort, medan han under övriga veckor behöver vara kvar i Stockholm. Inom de ramarna är han i övrigt flexibel kring ort och resor.",
      terms: [
        "geografisk flexibilitet",
        "flytta",
        "flyttbar",
        "arbeta på annan ort",
        "jobba på annan ort",
        "resor i jobbet",
        "Stockholm bas",
        "ojämna veckor",
      ],
      priority: 15,
    },
    {
      id: "additional-hybrid-remote",
      answer:
        "Magnus föredrar ett hybridupplägg med en blandning av kontorsnärvaro och distansarbete. Han upplever att helt distansbaserat arbete kan minska sammanhang, gemenskap och nyttiga synergier mellan kollegor, men är samtidigt öppen för olika upplägg och har inga helt låsta ramar.",
      terms: [
        "hybrid",
        "remote",
        "distansarbete",
        "kontor",
        "jobba hemifrån",
        "arbetsupplägg",
        "hybridarbete",
      ],
      priority: 13,
    },
    {
      id: "additional-availability",
      answer: "Magnus är tillgänglig omgående.",
      terms: [
        "tillgänglighet",
        "tillgänglig omgående",
        "när kan Magnus börja",
        "startdatum",
        "uppsägningstid",
        "börja omgående",
      ],
      priority: 18,
    },
    {
      id: "additional-languages-practical",
      answer:
        "Magnus har svenska som modersmål och talar engelska professionellt. Hans tyska är begränsad, även om han förstår en hel del. Spanskan och portugisiskan är mycket begränsade och tillför ingen professionell arbetsförmåga.",
      terms: [
        "språk",
        "engelska professionellt",
        "professionell engelska",
        "kan Magnus arbeta på engelska",
        "tyska",
        "spanska",
        "portugisiska",
        "språkkunskaper",
      ],
      priority: 14,
    },
    {
      id: "additional-favorite-color",
      answer: "Magnus favoritfärg är lila.",
      terms: [
        "favoritfärg",
        "vilken är Magnus favoritfärg",
        "vilken färg gillar Magnus",
        "lila",
      ],
      priority: 18,
    },
    {
      id: "additional-interests",
      answer:
        "På fritiden tränar Magnus framför allt på gym och springer. Vintertid åker han utförsåkning och längdskidor. Han lyssnar mycket på populärmusik men har en särskild fallenhet för trance och hårdrock, och spelar lite gitarr även om det blivit mindre på senare år. Han håller också på med korttrolleri och kortillusioner, vilket han tycker är både roligt och utmanande.",
      terms: [
        "intressen",
        "hobbys",
        "fritid",
        "utanför jobbet",
        "gym",
        "löpning",
        "skidor",
        "längdskidor",
        "musik",
        "trance",
        "hårdrock",
        "gitarr",
        "korttrolleri",
        "korttrick",
        "kortillusioner",
      ],
      priority: 12,
    },
    {
      id: "additional-personality-outside-work",
      answer:
        "Magnus tror att människor som känner honom väl skulle beskriva honom som social, trevlig och som en person de kan lita på. De skulle sannolikt också beskriva honom som en tidsoptimist som privat ibland kommer lite senare än avtalat.",
      terms: [
        "personlighet utanför jobbet",
        "hur är Magnus privat",
        "hur beskriver vänner Magnus",
        "vad skulle andra säga om Magnus",
        "hur skulle andra beskriva Magnus",
        "hur skulle personer som känner Magnus beskriva honom",
        "social",
        "pålitlig",
        "tidsoptimist",
        "sen",
      ],
      priority: 11,
    },
    {
      id: "additional-parachute-ranger-impact",
      answer:
        "Magnus upplever att fallskärmsjägartjänsten lärde honom att man klarar betydligt mer än man först föreställer sig. Han ser den erfarenheten som en anledning till att det krävs mycket för att han ska ge upp när något är svårt.",
      terms: [
        "fallskärmsjägare",
        "militärtjänst",
        "militär bakgrund",
        "jägartjänst",
        "motståndskraft",
        "ge upp",
      ],
      priority: 13,
    },
    {
      id: "additional-career-breadth",
      answer:
        "Magnus har medvetet byggt en bred erfarenhet inom försäljning, affärsutveckling, strategi, marknad, juridiska och regulatoriska frågor samt projekt eftersom han uppskattar arbetsvidgning. Han har generellt trivts bäst i roller där flera områden kan kombineras i stället för att bara fokusera på en smal funktion.",
      terms: [
        "karriärval",
        "karriärbredd",
        "varför olika roller",
        "försäljning affärsutveckling strategi marknad",
        "juridik regulatorik",
        "bred erfarenhet",
        "arbetsvidgning",
      ],
      priority: 13,
    },
    {
      id: "additional-differentiator",
      answer:
        "Magnus ser sin förmåga att snabbt sätta sig in i nya frågor, ta tag i arbetet och producera i högt tempo som en viktig skillnad mot många andra kandidater. Samtidigt vill han inte att arbetet ska bli så allvarligt att relationerna runt omkring försvinner; även vid hög arbetsbelastning försöker han vara social, tillgänglig och ge kollegor tid och uppmärksamhet.",
      terms: [
        "vad skiljer Magnus från andra",
        "skillnad mot andra kandidater",
        "varför anställa Magnus",
        "unik styrka",
        "kandidatjämförelse",
        "vad gör Magnus annorlunda",
      ],
      priority: 16,
    },
    {
      id: "additional-logic-assessment",
      answer:
        "På Alva Labs logiktest fick Magnus 9 av 10, vilket klassificeras som över genomsnittet och motsvarar 93:e-98:e percentilen. Testet mäter hur effektivt man hanterar komplex information och drar korrekta slutsatser från den.",
      terms: [
        "logiktest",
        "logisk förmåga",
        "logiskt resonemang",
        "Alva logik",
        "logikpoäng",
        "9 av 10",
        "93:e percentilen",
        "98:e percentilen",
      ],
      priority: 18,
    },
    {
      id: "additional-personality-assessment-overview",
      answer:
        "I Alva Labs Big Five-test fick Magnus 6/10 i vänlighet, 7/10 i samvetsgrannhet, 7/10 i extraversion, 8/10 i emotionell stabilitet och 7/10 i öppenhet. Rapporten beskriver sammantaget en profil som är ihärdig, utåtriktad, motståndskraftig och innovativ, medan vänlighet ligger omkring genomsnittet.",
      terms: [
        "personlighetstest",
        "personlighetsbedömning",
        "Alva personlighet",
        "Big Five",
        "personlighetsprofil",
        "vänlighet samvetsgrannhet extraversion emotionell stabilitet öppenhet",
      ],
      priority: 17,
    },
    {
      id: "additional-personality-conscientiousness",
      answer:
        "Alva Labs placerar Magnus samvetsgrannhet på 7/10, i 69:e-84:e percentilen. Rapporten beskriver honom som ihärdig, målinriktad, hårt arbetande, strukturerad och organiserad, med en tendens att komma igång snabbt och slutföra sina uppgifter.",
      terms: [
        "samvetsgrannhet",
        "ihärdig",
        "målinriktad",
        "ordningsam",
        "strukturerad personlighet",
        "självdisciplin",
      ],
      priority: 15,
    },
    {
      id: "additional-personality-extraversion",
      answer:
        "Alva Labs placerar Magnus extraversion på 7/10, i 69:e-84:e percentilen. Rapporten beskriver honom som utåtriktad och social, med särskilt hög energinivå i 84:e-93:e percentilen. Social dominans ligger mer i mitten: han söker inte alltid ledarrollen men tar den ibland och uttrycker sin åsikt när det behövs.",
      terms: [
        "extraversion",
        "utåtriktad",
        "social personlighet",
        "energinivå",
        "social dominans",
        "energisk",
      ],
      priority: 15,
    },
    {
      id: "additional-personality-emotional-stability",
      answer:
        "Alva Labs placerar Magnus emotionella stabilitet på 8/10, i 84:e-93:e percentilen. Rapporten beskriver honom som motståndskraftig och generellt lugn under press, med optimism och stresstålighet också i 84:e-93:e percentilen.",
      terms: [
        "emotionell stabilitet",
        "stresstålighet",
        "under press",
        "motståndskraft",
        "optimism",
        "lugn under press",
        "stress",
      ],
      priority: 16,
    },
    {
      id: "additional-personality-openness",
      answer:
        "Alva Labs placerar Magnus öppenhet på 7/10, i 69:e-84:e percentilen. Rapporten beskriver honom som innovativ och intellektuellt nyfiken, intresserad av teoretiska problem, öppen för förändring och benägen att prova nya saker och sammanhang.",
      terms: [
        "öppenhet",
        "innovativ",
        "nyfikenhet",
        "intellektuellt nyfiken",
        "öppen för förändring",
        "förändringsbenägen",
        "nya saker",
      ],
      priority: 15,
    },
    {
      id: "additional-personality-agreeableness",
      answer:
        "Alva Labs placerar Magnus vänlighet på 6/10, i 50:e-69:e percentilen. Rapporten beskriver en genomsnittlig totalnivå: han kan vara rak när det behövs utan att söka onödig konfrontation. Artighet ligger högre, i 69:e-84:e percentilen, medan tillit ligger i 50:e-69:e percentilen.",
      terms: [
        "vänlighet",
        "artighet",
        "tillit",
        "rak",
        "konfrontation",
        "vänskaplig",
      ],
      priority: 14,
    },
    {
      id: "additional-personality-strengths-challenges",
      answer:
        "Alva Labs lyfter tre potentiella styrkor: att vara beslutsam och målinriktad när svårigheter uppstår, att sprida entusiasm och vara motståndskraftig mot motgångar samt att vara mycket produktiv i högt tempo. Potentiella utmaningar är att ibland glömma att vila på grund av höga ambitioner, underskatta problem genom optimism och ibland framstå som pådrivande när saker ska bli gjorda.",
      terms: [
        "personlighetsstyrkor",
        "personlighetsutmaningar",
        "Alva styrkor",
        "Alva utmaningar",
        "pådrivande",
        "höga ambitioner",
        "produktiv",
        "motgångar",
      ],
      priority: 15,
    },
    {
      id: "additional-personality-drivers-culture",
      answer:
        "Enligt Alva Labs är Magnus viktigaste drivande faktorer stimulans, kreativitet och autonomi. Kulturpreferenserna som lyfts i rapporten är innovativ, energisk och beslutsam.",
      terms: [
        "drivande faktorer",
        "motivationsfaktorer",
        "kulturpreferenser",
        "stimulans",
        "kreativitet",
        "autonomi",
        "innovativ energisk beslutsam",
      ],
      priority: 15,
    },
    {
      id: "additional-historical-assessment",
      answer:
        "En kompetensutvecklingsrapport från 2011 är äldre och bör inte användas som en fristående beskrivning av Magnus idag, men flera teman stämmer väl med hans nuvarande egenbeskrivning och senare Alva-resultat. Rapporten beskrev ett strukturerat och systematiskt arbetssätt, höga prestationskrav, en förmåga att snabbt se kärnan i komplexa problem, effektivt arbete både självständigt och i grupp samt en stark vilja att få saker gjorda. Den noterade också möjliga tendenser att underskatta tidsåtgång och ibland vara för pådrivande, vilket liknar utvecklingsområden som Magnus fortfarande själv känner igen.",
      terms: [
        "2011 rapport",
        "gammal rapport",
        "äldre bedömning",
        "kompetensutvecklingsrapport",
        "historisk bedömning",
        "bedömning över tid",
        "tester över tid",
      ],
      priority: 14,
    },
  ],
};
