// lib/config/desktop.ts

export const DESKTOP_PAGE_MAX_WIDTH_PX = 1280;
export const DESKTOP_PAGE_HORIZONTAL_PADDING_PX = 24;
export const DESKTOP_PAGE_TOP_PADDING_PX = 24;
export const DESKTOP_PAGE_BOTTOM_PADDING_PX = 96;
export const DESKTOP_SECTION_STACK_GAP_PX = 14;

export const DESKTOP_HEADER_HEIGHT_PX = 88;

export const DESKTOP_HEADER_WORDMARK_TEXT_SIZE_PX = 40;
export const DESKTOP_HEADER_WORDMARK_TEXT_WEIGHT = 600 as const;
export const DESKTOP_HEADER_WORDMARK_LINE_HEIGHT = 1;

export const DESKTOP_HEADER_SUBTITLE_TEXT_SIZE_PX = 14;
export const DESKTOP_HEADER_SUBTITLE_TEXT_WEIGHT = 500 as const;
export const DESKTOP_HEADER_SUBTITLE_LINE_HEIGHT = 1.25;
export const DESKTOP_HEADER_BRAND_STACK_GAP_PX = 12;

export const DESKTOP_HEADER_NAV_TEXT_SIZE_PX = 15;
export const DESKTOP_HEADER_NAV_TEXT_WEIGHT = 500 as const;
export const DESKTOP_HEADER_NAV_GAP_PX = 48;
export const DESKTOP_HEADER_NAV_OFFSET_X_PX = -40;
export const DESKTOP_HEADER_NAV_UNDERLINE_WIDTH_PX = 30;
export const DESKTOP_HEADER_NAV_UNDERLINE_HEIGHT_PX = 2;
export const DESKTOP_HEADER_NAV_UNDERLINE_OFFSET_TOP_PX = 6;
export const DESKTOP_HEADER_NAV_UNDERLINE_RADIUS_PX = 9999;

export const DESKTOP_SECTION_SCROLL_MARGIN_TOP_PX = 104;

export const DESKTOP_ABOUT_SECTION_PADDING_TOP_PX = 128;
export const DESKTOP_ABOUT_SECTION_PADDING_BOTTOM_PX = 72;

export const DESKTOP_STANDARD_SECTION_PADDING_TOP_PX = 72;
export const DESKTOP_STANDARD_SECTION_PADDING_BOTTOM_PX = 72;
export const DESKTOP_STANDARD_SECTION_WIDTH_PX = 740;

export const DESKTOP_HERO_GRID_LEFT_FRACTION = "0.8fr";
export const DESKTOP_HERO_GRID_RIGHT_FRACTION = "1.2fr";
export const DESKTOP_HERO_COLUMN_GAP_PX = 80;

export const DESKTOP_PROFILE_IMAGE_WIDTH_PX = 300;
export const DESKTOP_PROFILE_IMAGE_HEIGHT_PX = 390;
export const DESKTOP_PROFILE_IMAGE_RADIUS_PX = 10;
export const DESKTOP_PROFILE_IMAGE_OFFSET_X_PX = 32;

export const DESKTOP_ABOUT_TEXT_OFFSET_X_PX = -28;
export const DESKTOP_HERO_CONTENT_WIDTH_PX = 600;
export const DESKTOP_HERO_TEXT_COLUMN_GAP_PX = 28;

export const DESKTOP_HERO_HEADING_TEXT_SIZE_PX = 36;
export const DESKTOP_HERO_HEADING_TEXT_WEIGHT = 600 as const;
export const DESKTOP_HERO_HEADING_LINE_HEIGHT = 1.08;
export const DESKTOP_HERO_HEADING_LETTER_SPACING_EM = -0.04;

export const DESKTOP_SECTION_HEADING_TEXT_SIZE_PX = 36;
export const DESKTOP_SECTION_HEADING_TEXT_WEIGHT = 600 as const;
export const DESKTOP_SECTION_HEADING_LINE_HEIGHT = 1.08;
export const DESKTOP_SECTION_HEADING_LETTER_SPACING_EM = -0.04;

export const DESKTOP_SECTION_HEADING_UNDERLINE_WIDTH_PX = 50;
export const DESKTOP_SECTION_HEADING_UNDERLINE_HEIGHT_PX = 2;
export const DESKTOP_SECTION_HEADING_UNDERLINE_OFFSET_TOP_PX = 6;
export const DESKTOP_SECTION_HEADING_UNDERLINE_RADIUS_PX = 9999;
export const DESKTOP_SECTION_HEADING_UNDERLINE_ANIMATION_DURATION_SECONDS = 5;

export const DESKTOP_BODY_TEXT_SIZE_PX = 16;
export const DESKTOP_BODY_TEXT_WEIGHT = 400 as const;
export const DESKTOP_BODY_LINE_HEIGHT = 1.7;
export const DESKTOP_BODY_LETTER_SPACING_EM = -0.01;

export const DESKTOP_CONTACT_LINK_TEXT_WEIGHT = 500 as const;

export const DESKTOP_STANDARD_SECTION_GAP_PX = 28;

export const DESKTOP_SKILLS_GRID_COLUMN_GAP_PX = 24;
export const DESKTOP_SKILLS_GRID_ROW_GAP_PX = 24;
export const DESKTOP_SKILLS_CARD_PADDING_X_PX = 28;
export const DESKTOP_SKILLS_CARD_PADDING_Y_PX = 26;
export const DESKTOP_SKILLS_CARD_RADIUS_PX = 10;
export const DESKTOP_SKILLS_CARD_TITLE_TEXT_SIZE_PX = 18;
export const DESKTOP_SKILLS_CARD_TITLE_TEXT_WEIGHT = 700 as const;
export const DESKTOP_SKILLS_CARD_TITLE_LINE_HEIGHT = 1.25;
export const DESKTOP_SKILLS_CARD_TITLE_MARGIN_BOTTOM_PX = 24;
export const DESKTOP_SKILLS_PILL_LIST_COLUMN_GAP_PX = 10;
export const DESKTOP_SKILLS_PILL_LIST_ROW_GAP_PX = 10;
export const DESKTOP_SKILLS_PILL_PADDING_X_PX = 14;
export const DESKTOP_SKILLS_PILL_PADDING_Y_PX = 8;
export const DESKTOP_SKILLS_PILL_RADIUS_PX = 22;
export const DESKTOP_SKILLS_PILL_TEXT_SIZE_PX = 14;
export const DESKTOP_SKILLS_PILL_TEXT_WEIGHT = 600 as const;
export const DESKTOP_SKILLS_PILL_LINE_HEIGHT = 1.2;

export const DESKTOP_DOWNLOAD_BLOCK_MARGIN_TOP_PX = 12;
export const DESKTOP_DOWNLOAD_BLOCK_GAP_PX = 0;
export const DESKTOP_DOWNLOAD_LIST_GAP_PX = 44;
export const DESKTOP_DOWNLOAD_LINK_TEXT_SIZE_PX = 17;
export const DESKTOP_DOWNLOAD_LINK_TEXT_WEIGHT = 500 as const;
export const DESKTOP_DOWNLOAD_LINK_GAP_PX = 8;

export const DESKTOP_DOWNLOAD_ICON_TAB_SIZE_PX = 26;
export const DESKTOP_DOWNLOAD_ICON_TAB_RADIUS_PX = 9999;
export const DESKTOP_DOWNLOAD_ICON_TAB_ICON_SIZE_PX = 18;

export const DESKTOP_RESUME_LIST_GAP_PX = 34;
export const DESKTOP_RESUME_LIST_PADDING_LEFT_PX = 48;
export const DESKTOP_RESUME_TIMELINE_GROUP_GAP_PX = 34;
export const DESKTOP_RESUME_TIMELINE_LINE_TOP_PX = 12;
export const DESKTOP_RESUME_TIMELINE_LINE_LEFT_PX = -34;
export const DESKTOP_RESUME_TIMELINE_MARKER_TOP_PX = 7;
export const DESKTOP_RESUME_TIMELINE_MARKER_LEFT_PX = -39;
export const DESKTOP_RESUME_TIMELINE_MARKER_SIZE_PX = 11;
export const DESKTOP_RESUME_ENTRY_GAP_PX = 16;
export const DESKTOP_RESUME_ENTRY_HEADER_GAP_PX = 4;
export const DESKTOP_RESUME_ENTRY_BODY_GAP_PX = 8;
export const DESKTOP_RESUME_ROLE_TITLE_TEXT_SIZE_PX = 18;
export const DESKTOP_RESUME_ROLE_TITLE_TEXT_WEIGHT = 700 as const;
export const DESKTOP_RESUME_META_TEXT_SIZE_PX = 16;
export const DESKTOP_RESUME_META_TEXT_WEIGHT = 400 as const;
export const DESKTOP_RESUME_DESCRIPTION_TEXT_SIZE_PX = 14;
export const DESKTOP_RESUME_DESCRIPTION_TEXT_WEIGHT = 400 as const;
export const DESKTOP_RESUME_DESCRIPTION_LABEL_TEXT_WEIGHT = 600 as const;
export const DESKTOP_RESUME_DESCRIPTION_LINE_HEIGHT = 1.6;

export const DESKTOP_EDUCATION_COLUMN_GAP_PX = 28;
export const DESKTOP_EDUCATION_ROW_GAP_PX = 24;
export const DESKTOP_EDUCATION_LIST_GAP_PX = 26;
export const DESKTOP_EDUCATION_ENTRY_GAP_PX = 4;
export const DESKTOP_EDUCATION_TITLE_TEXT_SIZE_PX = 17;
export const DESKTOP_EDUCATION_TITLE_TEXT_WEIGHT = 600 as const;
export const DESKTOP_EDUCATION_INSTITUTION_TEXT_SIZE_PX = 16;
export const DESKTOP_EDUCATION_INSTITUTION_TEXT_WEIGHT = 400 as const;
export const DESKTOP_EDUCATION_PERIOD_TEXT_SIZE_PX = 16;
export const DESKTOP_EDUCATION_PERIOD_TEXT_WEIGHT = 400 as const;
export const DESKTOP_EDUCATION_THESIS_LABEL_TEXT_SIZE_PX = 12;
export const DESKTOP_EDUCATION_THESIS_TEXT_SIZE_PX = 14;