// lib/config/mobile.ts

export const MOBILE_PAGE_HORIZONTAL_PADDING_PX = 20;
export const MOBILE_PAGE_TOP_PADDING_PX = 90;
export const MOBILE_PAGE_BOTTOM_PADDING_PX = 128;
export const MOBILE_SECTION_STACK_GAP_PX = 14;

export const MOBILE_TOP_OVERLAY_HEIGHT_PX = 94;
export const MOBILE_TOP_OVERLAY_HORIZONTAL_PADDING_PX = 20;

export const MOBILE_TOP_OVERLAY_WORDMARK_TEXT_SIZE_PX = 30;
export const MOBILE_TOP_OVERLAY_WORDMARK_TEXT_WEIGHT = 600 as const;
export const MOBILE_TOP_OVERLAY_WORDMARK_LINE_HEIGHT = 1;

export const MOBILE_TOP_OVERLAY_SUBTITLE_TEXT_SIZE_PX = 11;
export const MOBILE_TOP_OVERLAY_SUBTITLE_TEXT_WEIGHT = 500 as const;
export const MOBILE_TOP_OVERLAY_SUBTITLE_LINE_HEIGHT = 1.5;
export const MOBILE_TOP_OVERLAY_BRAND_STACK_GAP_PX = 10;

export const MOBILE_BOTTOM_NAV_HEIGHT_PX = 72;
export const MOBILE_BOTTOM_NAV_SIDE_PADDING_PX = 16;
export const MOBILE_BOTTOM_NAV_PADDING_TOP_PX = 8;
export const MOBILE_BOTTOM_NAV_PADDING_BOTTOM_PX = 10;

export const MOBILE_BOTTOM_NAV_ITEM_GAP_PX = 4;
export const MOBILE_BOTTOM_NAV_ICON_SIZE_PX = 20;

export const MOBILE_BOTTOM_NAV_LABEL_TEXT_SIZE_PX = 11;
export const MOBILE_BOTTOM_NAV_LABEL_TEXT_WEIGHT = 500 as const;
export const MOBILE_BOTTOM_NAV_LABEL_LINE_HEIGHT_PX = 14;

export const MOBILE_BOTTOM_NAV_OVERLINE_WIDTH_PX = 24;
export const MOBILE_BOTTOM_NAV_OVERLINE_HEIGHT_PX = 2;

export const MOBILE_OVERLAY_SCROLL_DIRECTION_THRESHOLD_PX = 8;

export const MOBILE_BOTTOM_SHEET_RADIUS_PX = 28;
export const MOBILE_BOTTOM_SHEET_MAX_VIEWPORT_OFFSET_PX = 16;

export const MOBILE_BOTTOM_SHEET_SIDE_PADDING_PX = 24;
export const MOBILE_BOTTOM_SHEET_MENU_PADDING_TOP_PX = 0;
export const MOBILE_BOTTOM_SHEET_MENU_PADDING_BOTTOM_PX = 24;

export const MOBILE_BOTTOM_SHEET_HANDLE_WIDTH_PX = 60;
export const MOBILE_BOTTOM_SHEET_HANDLE_HEIGHT_PX = 3;
export const MOBILE_BOTTOM_SHEET_HANDLE_MARGIN_TOP_PX = 12;
export const MOBILE_BOTTOM_SHEET_HANDLE_MARGIN_BOTTOM_PX = 20;

export const MOBILE_BOTTOM_SHEET_ITEM_GAP_PX = 6;

export const MOBILE_CONTACT_SHEET_ICON_SIZE_PX = 20;
export const MOBILE_CONTACT_SHEET_ITEM_GAP_PX = 12;
export const MOBILE_CONTACT_SHEET_ITEM_PADDING_Y_PX = 12;
export const MOBILE_CONTACT_SHEET_ITEM_RADIUS_PX = 18;
export const MOBILE_CONTACT_SHEET_ITEM_TEXT_SIZE_PX = 16;
export const MOBILE_CONTACT_SHEET_ITEM_TEXT_WEIGHT = 500 as const;
export const MOBILE_CONTACT_SHEET_ITEM_LINE_HEIGHT_PX = 22;

export const MOBILE_CONTACT_SHEET_CLOSE_PADDING_Y_PX = 18;
export const MOBILE_CONTACT_SHEET_CLOSE_TEXT_SIZE_PX = 14;
export const MOBILE_CONTACT_SHEET_CLOSE_TEXT_WEIGHT = 500 as const;
export const MOBILE_CONTACT_SHEET_CLOSE_LINE_HEIGHT_PX = 20;

export const MOBILE_SECTION_SCROLL_MARGIN_TOP_PX = 112;

export const MOBILE_ABOUT_SECTION_PADDING_TOP_PX = 32;
export const MOBILE_ABOUT_SECTION_PADDING_BOTTOM_PX = 32;

export const MOBILE_STANDARD_SECTION_PADDING_TOP_PX = 32;
export const MOBILE_STANDARD_SECTION_PADDING_BOTTOM_PX = 32;

export const MOBILE_HERO_LAYOUT_GAP_PX = 36;

export const MOBILE_PROFILE_IMAGE_WIDTH_PX = 210;
export const MOBILE_PROFILE_IMAGE_HEIGHT_PX = 270;
export const MOBILE_PROFILE_IMAGE_RADIUS_PX = 10;

export const MOBILE_HERO_CONTENT_WIDTH_PX = 420;
export const MOBILE_HERO_TEXT_COLUMN_GAP_PX = 24;

export const MOBILE_HERO_HEADING_TEXT_SIZE_PX = 26;
export const MOBILE_HERO_HEADING_TEXT_WEIGHT = 600 as const;
export const MOBILE_HERO_HEADING_LINE_HEIGHT = 1.08;
export const MOBILE_HERO_HEADING_LETTER_SPACING_EM = -0.04;

export const MOBILE_SECTION_HEADING_TEXT_SIZE_PX = 30;
export const MOBILE_SECTION_HEADING_TEXT_WEIGHT = 600 as const;
export const MOBILE_SECTION_HEADING_LINE_HEIGHT = 1.08;
export const MOBILE_SECTION_HEADING_LETTER_SPACING_EM = -0.04;

export const MOBILE_SECTION_HEADING_UNDERLINE_WIDTH_PX = 40;
export const MOBILE_SECTION_HEADING_UNDERLINE_HEIGHT_PX = 2;
export const MOBILE_SECTION_HEADING_UNDERLINE_OFFSET_TOP_PX = 4;
export const MOBILE_SECTION_HEADING_UNDERLINE_RADIUS_PX = 9999;
export const MOBILE_SECTION_HEADING_UNDERLINE_ANIMATION_DURATION_SECONDS = 5;

export const MOBILE_BODY_TEXT_SIZE_PX = 15;
export const MOBILE_BODY_TEXT_WEIGHT = 400 as const;
export const MOBILE_BODY_LINE_HEIGHT = 1.65;
export const MOBILE_BODY_LETTER_SPACING_EM = -0.01;

export const MOBILE_STANDARD_SECTION_GAP_PX = 24;

export const MOBILE_SKILLS_GRID_ROW_GAP_PX = 18;
export const MOBILE_SKILLS_CARD_PADDING_X_PX = 20;
export const MOBILE_SKILLS_CARD_PADDING_Y_PX = 22;
export const MOBILE_SKILLS_CARD_RADIUS_PX = 10;
export const MOBILE_SKILLS_CARD_TITLE_TEXT_SIZE_PX = 17;
export const MOBILE_SKILLS_CARD_TITLE_TEXT_WEIGHT = 700 as const;
export const MOBILE_SKILLS_CARD_TITLE_LINE_HEIGHT = 1.25;
export const MOBILE_SKILLS_CARD_TITLE_MARGIN_BOTTOM_PX = 20;
export const MOBILE_SKILLS_PILL_LIST_COLUMN_GAP_PX = 8;
export const MOBILE_SKILLS_PILL_LIST_ROW_GAP_PX = 8;
export const MOBILE_SKILLS_PILL_PADDING_X_PX = 12;
export const MOBILE_SKILLS_PILL_PADDING_Y_PX = 7;
export const MOBILE_SKILLS_PILL_RADIUS_PX = 22;
export const MOBILE_SKILLS_PILL_TEXT_SIZE_PX = 13;
export const MOBILE_SKILLS_PILL_TEXT_WEIGHT = 600 as const;
export const MOBILE_SKILLS_PILL_LINE_HEIGHT = 1.2;

export const MOBILE_DOWNLOAD_BLOCK_MARGIN_TOP_PX = 8;
export const MOBILE_DOWNLOAD_BLOCK_GAP_PX = 0;
export const MOBILE_DOWNLOAD_LIST_GAP_PX = 8;
export const MOBILE_DOWNLOAD_LINK_TEXT_SIZE_PX = 17;
export const MOBILE_DOWNLOAD_LINK_TEXT_WEIGHT = 500 as const;
export const MOBILE_DOWNLOAD_LINK_GAP_PX = 8;

export const MOBILE_DOWNLOAD_ICON_TAB_SIZE_PX = 24;
export const MOBILE_DOWNLOAD_ICON_TAB_RADIUS_PX = 9999;
export const MOBILE_DOWNLOAD_ICON_TAB_ICON_SIZE_PX = 18;

export const MOBILE_RESUME_LIST_GAP_PX = 32;
export const MOBILE_RESUME_LIST_PADDING_LEFT_PX = 28;
export const MOBILE_RESUME_ENTRY_GAP_PX = 14;
export const MOBILE_RESUME_ENTRY_HEADER_GAP_PX = 4;
export const MOBILE_RESUME_ENTRY_BODY_GAP_PX = 8;
export const MOBILE_RESUME_TIMELINE_GROUP_GAP_PX = 32;
export const MOBILE_RESUME_TIMELINE_LINE_TOP_PX = 11;
export const MOBILE_RESUME_TIMELINE_LINE_LEFT_PX = -18;
export const MOBILE_RESUME_TIMELINE_MARKER_TOP_PX = 7;
export const MOBILE_RESUME_TIMELINE_MARKER_LEFT_PX = -22;
export const MOBILE_RESUME_TIMELINE_MARKER_SIZE_PX = 9;
export const MOBILE_RESUME_ROLE_TITLE_TEXT_SIZE_PX = 17;
export const MOBILE_RESUME_ROLE_TITLE_TEXT_WEIGHT = 700 as const;
export const MOBILE_RESUME_META_TEXT_SIZE_PX = 15;
export const MOBILE_RESUME_META_TEXT_WEIGHT = 400 as const;
export const MOBILE_RESUME_RESPONSIBILITIES_TEXT_SIZE_PX = 15;
export const MOBILE_RESUME_RESPONSIBILITIES_TEXT_WEIGHT = 500 as const;
export const MOBILE_RESUME_DESCRIPTION_TEXT_SIZE_PX = 13;
export const MOBILE_RESUME_DESCRIPTION_TEXT_WEIGHT = 400 as const;
export const MOBILE_RESUME_DESCRIPTION_GAP_PX = 4;
export const MOBILE_RESUME_DESCRIPTION_LINE_HEIGHT = 1.6;

export const MOBILE_EDUCATION_COLUMN_GAP_PX = 28;
export const MOBILE_EDUCATION_ROW_GAP_PX = 24;
export const MOBILE_EDUCATION_LIST_GAP_PX = 24;
export const MOBILE_EDUCATION_ENTRY_GAP_PX = 4;
export const MOBILE_EDUCATION_TITLE_TEXT_SIZE_PX = 16;
export const MOBILE_EDUCATION_TITLE_TEXT_WEIGHT = 600 as const;
export const MOBILE_EDUCATION_INSTITUTION_TEXT_SIZE_PX = 15;
export const MOBILE_EDUCATION_INSTITUTION_TEXT_WEIGHT = 400 as const;
export const MOBILE_EDUCATION_PERIOD_TEXT_SIZE_PX = 15;
export const MOBILE_EDUCATION_PERIOD_TEXT_WEIGHT = 400 as const;